# 04 - Hidden Insight Mining

            Mục tiêu:

            - Đọc kết quả insight mining.
            - Kiểm tra các pattern/rule mạnh.
            - Kết nối insight với feature engineering.
            - Tránh leakage: insight nên được tìm trên train và kiểm tra stability validation.

In [1]:
from pathlib import Path
import sys
import json

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.append(str(PROJECT_ROOT))

pd.set_option("display.max_columns", 300)
pd.set_option("display.width", 200)

print("PROJECT_ROOT:", PROJECT_ROOT)

PROJECT_ROOT: e:\fraud-detection-project

In [2]:
REPORT_DIR = PROJECT_ROOT / "data" / "reports"
INSIGHT_DIR = REPORT_DIR / "insights"

print("INSIGHT_DIR exists:", INSIGHT_DIR.exists())

INSIGHT_DIR exists: True

In [3]:
if INSIGHT_DIR.exists():
    files = sorted(INSIGHT_DIR.glob("*.csv"))
    print("Insight files:", [f.name for f in files])

    for file in files:
        print("\n" + "=" * 100)
        print(file.name)
        display(pd.read_csv(file).head(30))
else:
    print("Chưa có thư mục insight. Hãy chạy scripts/03_run_insight_mining.py trước.")

Insight files: ['actionable_rules_train.csv', 'boolean_interaction_stability.csv', 'boolean_interactions_train.csv', 'boolean_interactions_validation.csv', 'business_segment_report_train.csv', 'business_segment_report_validation.csv', 'categorical_fraud_rate_train.csv', 'categorical_fraud_rate_validation.csv', 'categorical_pair_interactions_train.csv', 'categorical_pair_interactions_validation.csv', 'categorical_pair_stability.csv', 'categorical_pattern_stability.csv', 'feature_recommendations_train.csv', 'numeric_bin_fraud_rate_train.csv', 'numeric_bin_fraud_rate_validation.csv', 'numeric_pattern_stability.csv', 'priority_business_interactions_train.csv', 'priority_business_interactions_validation.csv', 'priority_interaction_stability.csv', 'segment_stability.csv', 'split_summary.csv', 'stable_boolean_interactions.csv', 'stable_categorical_pair_interactions.csv', 'stable_categorical_patterns.csv', 'stable_numeric_patterns.csv', 'stable_priority_interactions.csv', 'stable_segments.csv', 'strong_categorical_patterns_train.csv', 'strong_numeric_patterns_train.csv', 'train_behavior_thresholds.csv', 'train_features_preview.csv', 'train_valid_global_fraud_rate.csv', 'validation_features_preview.csv']

====================================================================================================
actionable_rules_train.csv

,rule,support,support_rate,fraud_count,fraud_rate,global_fraud_rate,fraud_rate_diff,lift,order,strength,business_interpretation,feature_a,value_a,feature_b,value_b
0,low_night_ratio_flag AND low_mcc_entropy_x_car...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,2,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...,NaN,NaN,NaN,NaN
1,card_not_present_flag AND low_mcc_entropy_x_lo...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,2,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...,NaN,NaN,NaN,NaN
2,low_mcc_entropy_x_low_night_ratio AND low_mcc_...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,2,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...,NaN,NaN,NaN,NaN
3,low_mcc_entropy_flag AND low_night_ratio_flag ...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...,NaN,NaN,NaN,NaN
4,low_mcc_entropy_flag AND low_night_ratio_flag ...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...,NaN,NaN,NaN,NaN
5,low_mcc_entropy_flag AND card_not_present_flag...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...,NaN,NaN,NaN,NaN
6,low_mcc_entropy_flag AND low_mcc_entropy_x_low...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...,NaN,NaN,NaN,NaN
7,low_night_ratio_flag AND card_not_present_flag...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...,NaN,NaN,NaN,NaN
8,low_night_ratio_flag AND card_not_present_flag...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...,NaN,NaN,NaN,NaN
9,low_night_ratio_flag AND low_mcc_entropy_x_low...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...,NaN,NaN,NaN,NaN
10,card_not_present_flag AND low_mcc_entropy_x_lo...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...,NaN,NaN,NaN,NaN
11,low_mcc_entropy AND low_night_ratio AND card_n...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...,NaN,NaN,NaN,NaN
12,low_mcc_entropy_flag AND low_night_ratio_flag,696,0.009943,181,0.260057,0.025471,0.234586,10.209772,2,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...,NaN,NaN,NaN,NaN
13,low_mcc_entropy_flag AND low_mcc_entropy_x_low...,696,0.009943,181,0.260057,0.025471,0.234586,10.209772,2,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...,NaN,NaN,NaN,NaN
14,low_night_ratio_flag AND low_mcc_entropy_x_low...,696,0.009943,181,0.260057,0.025471,0.234586,10.209772,2,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...,NaN,NaN,NaN,NaN
15,low_mcc_entropy_flag AND low_night_ratio_flag ...,696,0.009943,181,0.260057,0.025471,0.234586,10.209772,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...,NaN,NaN,NaN,NaN
16,low_mcc_entropy AND low_night_ratio,696,0.009943,181,0.260057,0.025471,0.234586,10.209772,2,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...,NaN,NaN,NaN,NaN
17,low_spending_trend_flag AND low_mcc_entropy_x_...,481,0.006871,121,0.251559,0.025471,0.226088,9.876134,2,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...,NaN,NaN,NaN,NaN
18,card_not_present_flag AND low_mcc_entropy_x_lo...,481,0.006871,121,0.251559,0.025471,0.226088,9.876134,2,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...,NaN,NaN,NaN,NaN
19,low_mcc_entropy_x_low_spending_trend AND low_m...,481,0.006871,121,0.251559,0.025471,0.226088,9.876134,2,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...,NaN,NaN,NaN,NaN
20,low_mcc_entropy_flag AND low_spending_trend_fl...,481,0.006871,121,0.251559,0.025471,0.226088,9.876134,3,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...,NaN,NaN,NaN,NaN
21,low_mcc_entropy_flag AND low_spending_trend_fl...,481,0.006871,121,0.251559,0.025471,0.226088,9.876134,3,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...,NaN,NaN,NaN,NaN
22,low_mcc_entropy_flag AND card_not_present_flag...,481,0.006871,121,0.251559,0.025471,0.226088,9.876134,3,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...,NaN,NaN,NaN,NaN
23,low_mcc_entropy_flag AND low_mcc_entropy_x_low...,481,0.006871,121,0.251559,0.025471,0.226088,9.876134,3,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...,NaN,NaN,NaN,NaN
24,low_spending_trend_flag AND card_not_present_f...,481,0.006871,121,0.251559,0.025471,0.226088,9.876134,3,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...,NaN,NaN,NaN,NaN
25,low_spending_trend_flag AND card_not_present_f...,481,0.006871,121,0.251559,0.025471,0.226088,9.876134,3,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...,NaN,NaN,NaN,NaN
26,low_spending_trend_flag AND low_mcc_entropy_x_...,481,0.006871,121,0.251559,0.025471,0.226088,9.876134,3,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...,NaN,NaN,NaN,NaN
27,card_not_present_flag AND low_mcc_entropy_x_lo...,481,0.006871,121,0.251559,0.025471,0.226088,9.876134,3,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...,NaN,NaN,NaN,NaN
28,high_max_amount_30d_flag AND low_mcc_entropy_x...,469,0.006700,114,0.243070,0.025471,0.217599,9.542863,2,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...,NaN,NaN,NaN,NaN
29,card_not_present_flag AND low_mcc_entropy_x_hi...,469,0.006700,114,0.243070,0.025471,0.217599,9.542863,2,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...,NaN,NaN,NaN,NaN

====================================================================================================
boolean_interaction_stability.csv

,rule,support_train,fraud_count_train,fraud_rate_train,global_fraud_rate_train,fraud_rate_diff_train,lift_train,support_valid,fraud_count_valid,fraud_rate_valid,global_fraud_rate_valid,fraud_rate_diff_valid,lift_valid,lift_diff_valid_train,lift_ratio_valid_train,fraud_rate_diff_valid_train
0,high_max_amount_30d_flag AND low_country_diver...,354,58,0.163842,0.025471,0.138370,6.432376,83,23,0.277108,0.0252,0.251908,10.996366,4.563990,1.709534,0.113267
1,low_night_ratio_flag AND low_mcc_entropy_x_car...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
2,card_not_present_flag AND low_mcc_entropy_x_lo...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
3,low_mcc_entropy_x_low_night_ratio AND low_mcc_...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
4,low_mcc_entropy_flag AND low_night_ratio_flag ...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
5,low_mcc_entropy_flag AND low_night_ratio_flag ...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
6,low_mcc_entropy_flag AND card_not_present_flag...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
7,low_mcc_entropy_flag AND low_mcc_entropy_x_low...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
8,low_night_ratio_flag AND card_not_present_flag...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
9,low_night_ratio_flag AND card_not_present_flag...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
10,low_night_ratio_flag AND low_mcc_entropy_x_low...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
11,card_not_present_flag AND low_mcc_entropy_x_lo...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
12,high_max_amount_30d_flag AND low_mcc_entropy_x...,469,114,0.243070,0.025471,0.217599,9.542863,89,21,0.235955,0.0252,0.210755,9.363296,-0.179567,0.981183,-0.007115
13,card_not_present_flag AND low_mcc_entropy_x_hi...,469,114,0.243070,0.025471,0.217599,9.542863,89,21,0.235955,0.0252,0.210755,9.363296,-0.179567,0.981183,-0.007115
14,low_mcc_entropy_x_high_max_amount_30d AND low_...,469,114,0.243070,0.025471,0.217599,9.542863,89,21,0.235955,0.0252,0.210755,9.363296,-0.179567,0.981183,-0.007115
15,low_mcc_entropy_flag AND high_max_amount_30d_f...,469,114,0.243070,0.025471,0.217599,9.542863,89,21,0.235955,0.0252,0.210755,9.363296,-0.179567,0.981183,-0.007115
16,low_mcc_entropy_flag AND high_max_amount_30d_f...,469,114,0.243070,0.025471,0.217599,9.542863,89,21,0.235955,0.0252,0.210755,9.363296,-0.179567,0.981183,-0.007115
17,low_mcc_entropy_flag AND card_not_present_flag...,469,114,0.243070,0.025471,0.217599,9.542863,89,21,0.235955,0.0252,0.210755,9.363296,-0.179567,0.981183,-0.007115
18,low_mcc_entropy_flag AND low_mcc_entropy_x_hig...,469,114,0.243070,0.025471,0.217599,9.542863,89,21,0.235955,0.0252,0.210755,9.363296,-0.179567,0.981183,-0.007115
19,high_max_amount_30d_flag AND card_not_present_...,469,114,0.243070,0.025471,0.217599,9.542863,89,21,0.235955,0.0252,0.210755,9.363296,-0.179567,0.981183,-0.007115
20,high_max_amount_30d_flag AND card_not_present_...,469,114,0.243070,0.025471,0.217599,9.542863,89,21,0.235955,0.0252,0.210755,9.363296,-0.179567,0.981183,-0.007115
21,high_max_amount_30d_flag AND low_mcc_entropy_x...,469,114,0.243070,0.025471,0.217599,9.542863,89,21,0.235955,0.0252,0.210755,9.363296,-0.179567,0.981183,-0.007115
22,card_not_present_flag AND low_mcc_entropy_x_hi...,469,114,0.243070,0.025471,0.217599,9.542863,89,21,0.235955,0.0252,0.210755,9.363296,-0.179567,0.981183,-0.007115
23,low_mcc_entropy_flag AND high_max_amount_30d_flag,713,162,0.227209,0.025471,0.201738,8.920150,150,34,0.226667,0.0252,0.201467,8.994709,0.074559,1.008358,-0.000542
24,low_mcc_entropy_flag AND low_mcc_entropy_x_hig...,713,162,0.227209,0.025471,0.201738,8.920150,150,34,0.226667,0.0252,0.201467,8.994709,0.074559,1.008358,-0.000542
25,high_max_amount_30d_flag AND low_mcc_entropy_x...,713,162,0.227209,0.025471,0.201738,8.920150,150,34,0.226667,0.0252,0.201467,8.994709,0.074559,1.008358,-0.000542
26,low_mcc_entropy_flag AND high_max_amount_30d_f...,713,162,0.227209,0.025471,0.201738,8.920150,150,34,0.226667,0.0252,0.201467,8.994709,0.074559,1.008358,-0.000542
27,low_mcc_entropy_flag AND low_night_ratio_flag,696,181,0.260057,0.025471,0.234586,10.209772,159,36,0.226415,0.0252,0.201215,8.984726,-1.225046,0.880012,-0.033642
28,low_mcc_entropy_flag AND low_mcc_entropy_x_low...,696,181,0.260057,0.025471,0.234586,10.209772,159,36,0.226415,0.0252,0.201215,8.984726,-1.225046,0.880012,-0.033642
29,low_night_ratio_flag AND low_mcc_entropy_x_low...,696,181,0.260057,0.025471,0.234586,10.209772,159,36,0.226415,0.0252,0.201215,8.984726,-1.225046,0.880012,-0.033642

====================================================================================================
boolean_interactions_train.csv

,rule,support,support_rate,fraud_count,fraud_rate,global_fraud_rate,fraud_rate_diff,lift,order,strength,business_interpretation
0,low_night_ratio_flag AND low_mcc_entropy_x_car...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,2,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
1,card_not_present_flag AND low_mcc_entropy_x_lo...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,2,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
2,low_mcc_entropy_x_low_night_ratio AND low_mcc_...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,2,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
3,low_mcc_entropy_flag AND low_night_ratio_flag ...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
4,low_mcc_entropy_flag AND low_night_ratio_flag ...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
5,low_mcc_entropy_flag AND card_not_present_flag...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
6,low_mcc_entropy_flag AND low_mcc_entropy_x_low...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
7,low_night_ratio_flag AND card_not_present_flag...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
8,low_night_ratio_flag AND card_not_present_flag...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
9,low_night_ratio_flag AND low_mcc_entropy_x_low...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
10,card_not_present_flag AND low_mcc_entropy_x_lo...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
11,low_mcc_entropy_flag AND low_night_ratio_flag,696,0.009943,181,0.260057,0.025471,0.234586,10.209772,2,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
12,low_mcc_entropy_flag AND low_mcc_entropy_x_low...,696,0.009943,181,0.260057,0.025471,0.234586,10.209772,2,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
13,low_night_ratio_flag AND low_mcc_entropy_x_low...,696,0.009943,181,0.260057,0.025471,0.234586,10.209772,2,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
14,low_mcc_entropy_flag AND low_night_ratio_flag ...,696,0.009943,181,0.260057,0.025471,0.234586,10.209772,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
15,low_spending_trend_flag AND low_mcc_entropy_x_...,481,0.006871,121,0.251559,0.025471,0.226088,9.876134,2,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...
16,card_not_present_flag AND low_mcc_entropy_x_lo...,481,0.006871,121,0.251559,0.025471,0.226088,9.876134,2,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...
17,low_mcc_entropy_x_low_spending_trend AND low_m...,481,0.006871,121,0.251559,0.025471,0.226088,9.876134,2,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...
18,low_mcc_entropy_flag AND low_spending_trend_fl...,481,0.006871,121,0.251559,0.025471,0.226088,9.876134,3,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...
19,low_mcc_entropy_flag AND low_spending_trend_fl...,481,0.006871,121,0.251559,0.025471,0.226088,9.876134,3,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...
20,low_mcc_entropy_flag AND card_not_present_flag...,481,0.006871,121,0.251559,0.025471,0.226088,9.876134,3,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...
21,low_mcc_entropy_flag AND low_mcc_entropy_x_low...,481,0.006871,121,0.251559,0.025471,0.226088,9.876134,3,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...
22,low_spending_trend_flag AND card_not_present_f...,481,0.006871,121,0.251559,0.025471,0.226088,9.876134,3,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...
23,low_spending_trend_flag AND card_not_present_f...,481,0.006871,121,0.251559,0.025471,0.226088,9.876134,3,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...
24,low_spending_trend_flag AND low_mcc_entropy_x_...,481,0.006871,121,0.251559,0.025471,0.226088,9.876134,3,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...
25,card_not_present_flag AND low_mcc_entropy_x_lo...,481,0.006871,121,0.251559,0.025471,0.226088,9.876134,3,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...
26,high_max_amount_30d_flag AND low_mcc_entropy_x...,469,0.006700,114,0.243070,0.025471,0.217599,9.542863,2,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...
27,card_not_present_flag AND low_mcc_entropy_x_hi...,469,0.006700,114,0.243070,0.025471,0.217599,9.542863,2,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...
28,low_mcc_entropy_x_high_max_amount_30d AND low_...,469,0.006700,114,0.243070,0.025471,0.217599,9.542863,2,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...
29,low_mcc_entropy_flag AND high_max_amount_30d_f...,469,0.006700,114,0.243070,0.025471,0.217599,9.542863,3,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...

====================================================================================================
boolean_interactions_validation.csv

,rule,support,support_rate,fraud_count,fraud_rate,global_fraud_rate,fraud_rate_diff,lift,order,strength,business_interpretation
0,high_max_amount_30d_flag AND low_country_diver...,83,0.005533,23,0.277108,0.0252,0.251908,10.996366,3,VERY_STRONG,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
1,low_night_ratio_flag AND low_mcc_entropy_x_car...,94,0.006267,25,0.265957,0.0252,0.240757,10.553867,2,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
2,card_not_present_flag AND low_mcc_entropy_x_lo...,94,0.006267,25,0.265957,0.0252,0.240757,10.553867,2,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
3,low_mcc_entropy_x_low_night_ratio AND low_mcc_...,94,0.006267,25,0.265957,0.0252,0.240757,10.553867,2,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
4,low_mcc_entropy_flag AND low_night_ratio_flag ...,94,0.006267,25,0.265957,0.0252,0.240757,10.553867,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
5,low_mcc_entropy_flag AND low_night_ratio_flag ...,94,0.006267,25,0.265957,0.0252,0.240757,10.553867,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
6,low_mcc_entropy_flag AND card_not_present_flag...,94,0.006267,25,0.265957,0.0252,0.240757,10.553867,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
7,low_mcc_entropy_flag AND low_mcc_entropy_x_low...,94,0.006267,25,0.265957,0.0252,0.240757,10.553867,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
8,low_night_ratio_flag AND card_not_present_flag...,94,0.006267,25,0.265957,0.0252,0.240757,10.553867,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
9,low_night_ratio_flag AND card_not_present_flag...,94,0.006267,25,0.265957,0.0252,0.240757,10.553867,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
10,low_night_ratio_flag AND low_mcc_entropy_x_low...,94,0.006267,25,0.265957,0.0252,0.240757,10.553867,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
11,card_not_present_flag AND low_mcc_entropy_x_lo...,94,0.006267,25,0.265957,0.0252,0.240757,10.553867,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
12,high_max_amount_30d_flag AND low_mcc_entropy_x...,89,0.005933,21,0.235955,0.0252,0.210755,9.363296,2,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...
13,card_not_present_flag AND low_mcc_entropy_x_hi...,89,0.005933,21,0.235955,0.0252,0.210755,9.363296,2,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...
14,low_mcc_entropy_x_high_max_amount_30d AND low_...,89,0.005933,21,0.235955,0.0252,0.210755,9.363296,2,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...
15,low_mcc_entropy_flag AND high_max_amount_30d_f...,89,0.005933,21,0.235955,0.0252,0.210755,9.363296,3,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...
16,low_mcc_entropy_flag AND high_max_amount_30d_f...,89,0.005933,21,0.235955,0.0252,0.210755,9.363296,3,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...
17,low_mcc_entropy_flag AND card_not_present_flag...,89,0.005933,21,0.235955,0.0252,0.210755,9.363296,3,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...
18,low_mcc_entropy_flag AND low_mcc_entropy_x_hig...,89,0.005933,21,0.235955,0.0252,0.210755,9.363296,3,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...
19,high_max_amount_30d_flag AND card_not_present_...,89,0.005933,21,0.235955,0.0252,0.210755,9.363296,3,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...
20,high_max_amount_30d_flag AND card_not_present_...,89,0.005933,21,0.235955,0.0252,0.210755,9.363296,3,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...
21,high_max_amount_30d_flag AND low_mcc_entropy_x...,89,0.005933,21,0.235955,0.0252,0.210755,9.363296,3,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...
22,card_not_present_flag AND low_mcc_entropy_x_hi...,89,0.005933,21,0.235955,0.0252,0.210755,9.363296,3,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...
23,low_mcc_entropy_flag AND high_max_amount_30d_flag,150,0.010000,34,0.226667,0.0252,0.201467,8.994709,2,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...
24,low_mcc_entropy_flag AND low_mcc_entropy_x_hig...,150,0.010000,34,0.226667,0.0252,0.201467,8.994709,2,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...
25,high_max_amount_30d_flag AND low_mcc_entropy_x...,150,0.010000,34,0.226667,0.0252,0.201467,8.994709,2,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...
26,low_mcc_entropy_flag AND high_max_amount_30d_f...,150,0.010000,34,0.226667,0.0252,0.201467,8.994709,3,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...
27,tokenised_flag AND low_mcc_entropy_x_low_night...,75,0.005000,17,0.226667,0.0252,0.201467,8.994709,2,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
28,low_mcc_entropy_flag AND low_night_ratio_flag ...,75,0.005000,17,0.226667,0.0252,0.201467,8.994709,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
29,low_mcc_entropy_flag AND tokenised_flag AND lo...,75,0.005000,17,0.226667,0.0252,0.201467,8.994709,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...

====================================================================================================
business_segment_report_train.csv

,segment_name,description,support,support_rate,fraud_count,fraud_rate,global_fraud_rate,fraud_rate_diff,lift,strength,business_interpretation
0,very_low_mcc_entropy,"Nhóm cực thấp về mcc_entropy_30d, thường cần s...",3510,0.050143,339,0.096581,0.025471,0.071110,3.791746,STRONG,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
1,low_mcc_entropy,User có lịch sử MCC ít đa dạng. Đây là tín hiệ...,7009,0.100129,625,0.089171,0.025471,0.063700,3.500827,STRONG,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
2,low_night_ratio,User gần như không có thói quen giao dịch ban ...,7038,0.100543,511,0.072606,0.025471,0.047134,2.850482,MEDIUM,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
3,night_unusual,Giao dịch ban đêm nhưng user có lịch sử night_...,2401,0.034300,171,0.071220,0.025471,0.045749,2.796087,MEDIUM,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
4,high_max_amount_30d,User có max_amount_30d thuộc nhóm rất cao.,7000,0.100000,439,0.062714,0.025471,0.037243,2.462142,MEDIUM,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
5,low_country_diversity,User có lịch sử giao dịch ở ít quốc gia.,8464,0.120914,525,0.062027,0.025471,0.036556,2.435176,MEDIUM,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
6,has_chargeback_history,User có lịch sử chargeback trong 365 ngày.,10439,0.149129,306,0.029313,0.025471,0.003842,1.150825,LOW_SIGNAL,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
7,card_not_present,"Giao dịch không có thẻ vật lý, thường rủi ro h...",45672,0.652457,1201,0.026296,0.025471,0.000825,1.032380,LOW_SIGNAL,Giao dịch không có thẻ vật lý. Với fraud onlin...
8,night_transaction,Giao dịch hiện tại xảy ra ban đêm.,23339,0.333414,611,0.026179,0.025471,0.000708,1.027793,LOW_SIGNAL,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
9,tokenised_transaction,Giao dịch tokenised.,31516,0.450229,784,0.024876,0.025471,-0.000595,0.976634,LOW_SIGNAL,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
10,high_current_amount,Giao dịch hiện tại có amount thuộc nhóm cao.,7000,0.100000,173,0.024714,0.025471,-0.000757,0.970275,LOW_SIGNAL,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
11,high_ip_score,IP risk score thuộc nhóm cao.,7001,0.100014,172,0.024568,0.025471,-0.000904,0.964529,LOW_SIGNAL,IP có điểm rủi ro cao. Đây là tín hiệu kỹ thuậ...
12,high_amount_to_mean,Amount hiện tại cao hơn nhiều so với mean_amou...,7000,0.100000,147,0.021000,0.025471,-0.004471,0.824453,LOW_SIGNAL,Giao dịch có giá trị cao so với lịch sử. Đây l...
13,cross_border,Giao dịch xuyên biên giới.,13963,0.199471,280,0.020053,0.025471,-0.005418,0.787274,LOW_SIGNAL,Giao dịch xuyên biên giới. Risk phụ thuộc vào ...
14,high_device_diversity,User dùng nhiều thiết bị trong 30 ngày. Có thể...,8633,0.123329,125,0.014479,0.025471,-0.010992,0.568454,LOW_SIGNAL,User có nhiều thiết bị trong thời gian gần. Có...
15,high_decline_rate,User có tỷ lệ decline cao trong 30 ngày.,7070,0.101000,97,0.013720,0.025471,-0.011751,0.538641,LOW_SIGNAL,User có tỷ lệ giao dịch bị từ chối cao. Đây là...
16,high_amount_to_max,Amount hiện tại tiệm cận hoặc vượt max_amount_...,7000,0.100000,46,0.006571,0.025471,-0.018900,0.257992,LOW_SIGNAL,Giao dịch có giá trị cao so với lịch sử. Đây l...
17,low_spending_trend,Xu hướng chi tiêu 30 ngày thấp hoặc giảm.,0,0.000000,0,0.000000,0.025471,-0.025471,0.000000,WEAK_SUPPORT,Rule có tín hiệu thống kê. Cần kiểm tra suppor...

====================================================================================================
business_segment_report_validation.csv

,segment_name,description,support,support_rate,fraud_count,fraud_rate,global_fraud_rate,fraud_rate_diff,lift,strength,business_interpretation
0,night_unusual,Giao dịch ban đêm nhưng user có lịch sử night_...,496,0.033067,41,0.082661,0.0252,0.057461,3.280210,STRONG,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
1,very_low_mcc_entropy,"Nhóm cực thấp về mcc_entropy_30d, thường cần s...",750,0.050000,61,0.081333,0.0252,0.056133,3.227513,STRONG,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
2,high_max_amount_30d,User có max_amount_30d thuộc nhóm rất cao.,1500,0.100000,116,0.077333,0.0252,0.052133,3.068783,STRONG,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
3,low_night_ratio,User gần như không có thói quen giao dịch ban ...,1500,0.100000,110,0.073333,0.0252,0.048133,2.910053,MEDIUM,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
4,low_mcc_entropy,User có lịch sử MCC ít đa dạng. Đây là tín hiệ...,1503,0.100200,110,0.073187,0.0252,0.047987,2.904244,MEDIUM,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
5,low_country_diversity,User có lịch sử giao dịch ở ít quốc gia.,1842,0.122800,114,0.061889,0.0252,0.036689,2.455923,MEDIUM,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
6,has_chargeback_history,User có lịch sử chargeback trong 365 ngày.,2323,0.154867,69,0.029703,0.0252,0.004503,1.178689,LOW_SIGNAL,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
7,night_transaction,Giao dịch hiện tại xảy ra ban đêm.,4749,0.316600,132,0.027795,0.0252,0.002595,1.102989,LOW_SIGNAL,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
8,card_not_present,"Giao dịch không có thẻ vật lý, thường rủi ro h...",9663,0.644200,245,0.025354,0.0252,0.000154,1.006129,LOW_SIGNAL,Giao dịch không có thẻ vật lý. Với fraud onlin...
9,high_ip_score,IP risk score thuộc nhóm cao.,1500,0.100000,38,0.025333,0.0252,0.000133,1.005291,LOW_SIGNAL,IP có điểm rủi ro cao. Đây là tín hiệu kỹ thuậ...
10,tokenised_transaction,Giao dịch tokenised.,6736,0.449067,162,0.024050,0.0252,-0.001150,0.954360,LOW_SIGNAL,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
11,cross_border,Giao dịch xuyên biên giới.,3035,0.202333,63,0.020758,0.0252,-0.004442,0.823723,LOW_SIGNAL,Giao dịch xuyên biên giới. Risk phụ thuộc vào ...
12,high_amount_to_mean,Amount hiện tại cao hơn nhiều so với mean_amou...,1500,0.100000,30,0.020000,0.0252,-0.005200,0.793651,LOW_SIGNAL,Giao dịch có giá trị cao so với lịch sử. Đây l...
13,high_current_amount,Giao dịch hiện tại có amount thuộc nhóm cao.,1500,0.100000,29,0.019333,0.0252,-0.005867,0.767196,LOW_SIGNAL,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
14,high_device_diversity,User dùng nhiều thiết bị trong 30 ngày. Có thể...,1897,0.126467,34,0.017923,0.0252,-0.007277,0.711232,LOW_SIGNAL,User có nhiều thiết bị trong thời gian gần. Có...
15,high_decline_rate,User có tỷ lệ decline cao trong 30 ngày.,1519,0.101267,21,0.013825,0.0252,-0.011375,0.548607,LOW_SIGNAL,User có tỷ lệ giao dịch bị từ chối cao. Đây là...
16,high_amount_to_max,Amount hiện tại tiệm cận hoặc vượt max_amount_...,1500,0.100000,13,0.008667,0.0252,-0.016533,0.343915,LOW_SIGNAL,Giao dịch có giá trị cao so với lịch sử. Đây l...
17,low_spending_trend,Xu hướng chi tiêu 30 ngày thấp hoặc giảm.,0,0.000000,0,0.000000,0.0252,-0.025200,0.000000,WEAK_SUPPORT,Rule có tín hiệu thống kê. Cần kiểm tra suppor...

====================================================================================================
categorical_fraud_rate_train.csv

             feature         value  count  fraud_count  fraud_rate  global_fraud_rate  fraud_rate_diff      lift
0           currency           JPY   3890          116    0.029820           0.025471         0.004349  1.170726
1           currency           CAD   1954           58    0.029683           0.025471         0.004211  1.165333
2           currency           SGD   1978           56    0.028311           0.025471         0.002840  1.111497
3           currency           VND   2002           55    0.027473           0.025471         0.002001  1.078562
4           currency           CHF   2004           53    0.026447           0.025471         0.000976  1.038305
5           currency           USD  26780          707    0.026400           0.025471         0.000929  1.036467
6           currency           CNY   3355           88    0.026230           0.025471         0.000758  1.029762
7           currency           AUD   1996           51    0.025551           0.025471         0.000080  1.003128
8           currency           IDR   1943           47    0.024189           0.025471        -0.001282  0.949668
9           currency           INR   1960           47    0.023980           0.025471        -0.001492  0.941431
10          currency           EUR  10023          237    0.023646           0.025471        -0.001826  0.928319
11          currency           THB   2754           65    0.023602           0.025471        -0.001869  0.926608
12          currency           HKD   1985           46    0.023174           0.025471        -0.002298  0.909796
13          currency           GBP   5395          119    0.022057           0.025471        -0.003414  0.865969
14          currency           KRW   1981           38    0.019182           0.025471        -0.006289  0.753088
15   payment_channel   SMART_WATCH  10102          276    0.027321           0.025471         0.001850  1.072626
16   payment_channel    API_SERVER  10053          264    0.026261           0.025471         0.000789  1.030991
17   payment_channel           ATM   9867          253    0.025641           0.025471         0.000170  1.006658
18   payment_channel     IVR_PHONE   9902          249    0.025146           0.025471        -0.000325  0.987241
19   payment_channel  POS_TERMINAL   9843          246    0.024992           0.025471        -0.000479  0.981193
20   payment_channel    MOBILE_APP  10028          246    0.024531           0.025471        -0.000940  0.963091
21   payment_channel   WEB_BROWSER  10205          249    0.024400           0.025471        -0.001072  0.957928
22  merchant_country            AE   3561          105    0.029486           0.025471         0.004015  1.157615
23  merchant_country            US   3442          100    0.029053           0.025471         0.003581  1.140606
24  merchant_country            PH   3444           99    0.028746           0.025471         0.003274  1.128545
25  merchant_country            MY   3492           99    0.028351           0.025471         0.002879  1.113032
26  merchant_country            ZA   3557          100    0.028114           0.025471         0.002642  1.103730
27  merchant_country            VN   3516           96    0.027304           0.025471         0.001832  1.071937
28  merchant_country            DE   3461           94    0.027160           0.025471         0.001688  1.066284
29  merchant_country            GB   3514           94    0.026750           0.025471         0.001279  1.050202

====================================================================================================
categorical_fraud_rate_validation.csv

             feature         value  count  fraud_count  fraud_rate  global_fraud_rate  fraud_rate_diff      lift
0           currency           KRW    444           18    0.040541             0.0252         0.015341  1.608752
1           currency           GBP   1074           39    0.036313             0.0252         0.011113  1.440986
2           currency           SGD    460           16    0.034783             0.0252         0.009583  1.380262
3           currency           THB    597           18    0.030151             0.0252         0.004951  1.196458
4           currency           EUR   2146           56    0.026095             0.0252         0.000895  1.035518
5           currency           VND    392           10    0.025510             0.0252         0.000310  1.012310
6           currency           INR    443           11    0.024831             0.0252        -0.000369  0.985345
7           currency           USD   5694          133    0.023358             0.0252        -0.001842  0.926902
8           currency           AUD    432           10    0.023148             0.0252        -0.002052  0.918577
9           currency           HKD    407            9    0.022113             0.0252        -0.003087  0.877501
10          currency           CNY    724           16    0.022099             0.0252        -0.003101  0.876962
11          currency           CAD    424            9    0.021226             0.0252        -0.003974  0.842318
12          currency           JPY    873           18    0.020619             0.0252        -0.004581  0.818197
13          currency           IDR    413            8    0.019370             0.0252        -0.005830  0.768669
14          currency           CHF    477            7    0.014675             0.0252        -0.010525  0.582343
15   payment_channel    MOBILE_APP   2144           64    0.029851             0.0252         0.004651  1.184553
16   payment_channel           ATM   2121           57    0.026874             0.0252         0.001674  1.066433
17   payment_channel  POS_TERMINAL   2131           56    0.026279             0.0252         0.001079  1.042807
18   payment_channel    API_SERVER   2164           55    0.025416             0.0252         0.000216  1.008567
19   payment_channel   SMART_WATCH   2094           52    0.024833             0.0252        -0.000367  0.985431
20   payment_channel     IVR_PHONE   2205           52    0.023583             0.0252        -0.001617  0.935824
21   payment_channel   WEB_BROWSER   2141           42    0.019617             0.0252        -0.005583  0.778452
22  merchant_country            PH    749           29    0.038718             0.0252         0.013518  1.536440
23  merchant_country            KR    781           30    0.038412             0.0252         0.013212  1.524297
24  merchant_country            ID    736           24    0.032609             0.0252         0.007409  1.293996
25  merchant_country            VN    769           24    0.031209             0.0252         0.006009  1.238467
26  merchant_country            BR    751           20    0.026631             0.0252         0.001431  1.056792
27  merchant_country            AE    720           19    0.026389             0.0252         0.001189  1.047178
28  merchant_country            CA    760           20    0.026316             0.0252         0.001116  1.044277
29  merchant_country            MY    730           19    0.026027             0.0252         0.000827  1.032833

====================================================================================================
categorical_pair_interactions_train.csv

,rule,feature_a,value_a,feature_b,value_b,support,support_rate,fraud_count,fraud_rate,global_fraud_rate,fraud_rate_diff,lift,order,strength,business_interpretation
0,payment_channel=SMART_WATCH AND merchant_count...,payment_channel,SMART_WATCH,merchant_country,ZA,471,0.006729,24,0.050955,0.025471,0.025484,2.000493,2,MEDIUM,Một số tổ hợp kênh thanh toán và quốc gia merc...
1,payment_channel=IVR_PHONE AND merchant_country=TH,payment_channel,IVR_PHONE,merchant_country,TH,496,0.007086,21,0.042339,0.025471,0.016867,1.662204,2,WEAK,Một số tổ hợp kênh thanh toán và quốc gia merc...
2,payment_channel=WEB_BROWSER AND merchant_count...,payment_channel,WEB_BROWSER,merchant_country,US,496,0.007086,20,0.040323,0.025471,0.014851,1.583051,2,WEAK,Một số tổ hợp kênh thanh toán và quốc gia merc...
3,time_period=late_evening AND payment_channel=S...,time_period,late_evening,payment_channel,SMART_WATCH,887,0.012671,35,0.039459,0.025471,0.013987,1.549142,2,WEAK,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
4,payment_channel=SMART_WATCH AND merchant_count...,payment_channel,SMART_WATCH,merchant_country,CA,524,0.007486,20,0.038168,0.025471,0.012697,1.498461,2,LOW_SIGNAL,Một số tổ hợp kênh thanh toán và quốc gia merc...
5,payment_channel=IVR_PHONE AND merchant_country=CN,payment_channel,IVR_PHONE,merchant_country,CN,499,0.007129,19,0.038076,0.025471,0.012605,1.494857,2,LOW_SIGNAL,Một số tổ hợp kênh thanh toán và quốc gia merc...
6,payment_channel=API_SERVER AND merchant_countr...,payment_channel,API_SERVER,merchant_country,VN,509,0.007271,19,0.037328,0.025471,0.011857,1.465489,2,LOW_SIGNAL,Một số tổ hợp kênh thanh toán và quốc gia merc...
7,payment_channel=MOBILE_APP AND merchant_countr...,payment_channel,MOBILE_APP,merchant_country,AE,487,0.006957,18,0.036961,0.025471,0.011490,1.451076,2,LOW_SIGNAL,Một số tổ hợp kênh thanh toán và quốc gia merc...
8,day_name=Saturday AND payment_channel=MOBILE_APP,day_name,Saturday,payment_channel,MOBILE_APP,1469,0.020986,54,0.036760,0.025471,0.011288,1.443174,2,LOW_SIGNAL,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
9,card_entry_mode=CHIP AND auth_result=AVS_PASS,card_entry_mode,CHIP,auth_result,AVS_PASS,1453,0.020757,53,0.036476,0.025471,0.011005,1.432046,2,LOW_SIGNAL,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
10,payment_channel=SMART_WATCH AND merchant_count...,payment_channel,SMART_WATCH,merchant_country,DE,494,0.007057,18,0.036437,0.025471,0.010966,1.430514,2,LOW_SIGNAL,Một số tổ hợp kênh thanh toán và quốc gia merc...
11,payment_channel=SMART_WATCH AND merchant_count...,payment_channel,SMART_WATCH,merchant_country,HK,496,0.007086,18,0.036290,0.025471,0.010819,1.424746,2,LOW_SIGNAL,Một số tổ hợp kênh thanh toán và quốc gia merc...
12,payment_channel=SMART_WATCH AND term_location=...,payment_channel,SMART_WATCH,term_location,WEARABLE_PAY,1440,0.020571,52,0.036111,0.025471,0.010640,1.417710,2,LOW_SIGNAL,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
13,payment_channel=WEB_BROWSER AND merchant_count...,payment_channel,WEB_BROWSER,merchant_country,MY,499,0.007129,18,0.036072,0.025471,0.010601,1.416181,2,LOW_SIGNAL,Một số tổ hợp kênh thanh toán và quốc gia merc...
14,payment_channel=IVR_PHONE AND merchant_country=SG,payment_channel,IVR_PHONE,merchant_country,SG,501,0.007157,18,0.035928,0.025471,0.010457,1.410527,2,LOW_SIGNAL,Một số tổ hợp kênh thanh toán và quốc gia merc...
15,payment_channel=API_SERVER AND merchant_countr...,payment_channel,API_SERVER,merchant_country,IN,474,0.006771,17,0.035865,0.025471,0.010394,1.408047,2,LOW_SIGNAL,Một số tổ hợp kênh thanh toán và quốc gia merc...
16,card_entry_mode=MAGSTRIPE AND auth_result=3DS_...,card_entry_mode,MAGSTRIPE,auth_result,3DS_FAIL,1450,0.020714,52,0.035862,0.025471,0.010391,1.407933,2,LOW_SIGNAL,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
17,payment_channel=POS_TERMINAL AND merchant_coun...,payment_channel,POS_TERMINAL,merchant_country,PH,481,0.006871,17,0.035343,0.025471,0.009872,1.387556,2,LOW_SIGNAL,Một số tổ hợp kênh thanh toán và quốc gia merc...
18,payment_channel=SMART_WATCH AND merchant_count...,payment_channel,SMART_WATCH,merchant_country,MY,512,0.007314,18,0.035156,0.025471,0.009685,1.380223,2,LOW_SIGNAL,Một số tổ hợp kênh thanh toán và quốc gia merc...
19,day_name=Monday AND payment_channel=SMART_WATCH,day_name,Monday,payment_channel,SMART_WATCH,1425,0.020357,50,0.035088,0.025471,0.009616,1.377532,2,LOW_SIGNAL,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
20,payment_channel=ATM AND merchant_country=AU,payment_channel,ATM,merchant_country,AU,513,0.007329,18,0.035088,0.025471,0.009616,1.377532,2,LOW_SIGNAL,Một số tổ hợp kênh thanh toán và quốc gia merc...
21,payment_channel=API_SERVER AND merchant_countr...,payment_channel,API_SERVER,merchant_country,US,487,0.006957,17,0.034908,0.025471,0.009436,1.370461,2,LOW_SIGNAL,Một số tổ hợp kênh thanh toán và quốc gia merc...
22,payment_channel=IVR_PHONE AND merchant_country=ZA,payment_channel,IVR_PHONE,merchant_country,ZA,524,0.007486,18,0.034351,0.025471,0.008880,1.348615,2,LOW_SIGNAL,Một số tổ hợp kênh thanh toán và quốc gia merc...
23,payment_channel=POS_TERMINAL AND merchant_coun...,payment_channel,POS_TERMINAL,merchant_country,AE,500,0.007143,17,0.034000,0.025471,0.008529,1.334829,2,LOW_SIGNAL,Một số tổ hợp kênh thanh toán và quốc gia merc...
24,payment_channel=API_SERVER AND merchant_countr...,payment_channel,API_SERVER,merchant_country,JP,442,0.006314,15,0.033937,0.025471,0.008465,1.332342,2,LOW_SIGNAL,Một số tổ hợp kênh thanh toán và quốc gia merc...
25,payment_channel=POS_TERMINAL AND merchant_coun...,payment_channel,POS_TERMINAL,merchant_country,DE,502,0.007171,17,0.033865,0.025471,0.008393,1.329511,2,LOW_SIGNAL,Một số tổ hợp kênh thanh toán và quốc gia merc...
26,payment_channel=POS_TERMINAL AND term_location...,payment_channel,POS_TERMINAL,term_location,BRANCH_COUNTER,1418,0.020257,48,0.033850,0.025471,0.008379,1.328959,2,LOW_SIGNAL,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
27,day_name=Tuesday AND payment_channel=IVR_PHONE,day_name,Tuesday,payment_channel,IVR_PHONE,1392,0.019886,47,0.033764,0.025471,0.008293,1.325578,2,LOW_SIGNAL,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
28,payment_channel=SMART_WATCH AND merchant_count...,payment_channel,SMART_WATCH,merchant_country,GB,475,0.006786,16,0.033684,0.025471,0.008213,1.322431,2,LOW_SIGNAL,Một số tổ hợp kênh thanh toán và quốc gia merc...
29,day_name=Monday AND payment_channel=API_SERVER,day_name,Monday,payment_channel,API_SERVER,1432,0.020457,48,0.033520,0.025471,0.008048,1.315967,2,LOW_SIGNAL,Rule có tín hiệu thống kê. Cần kiểm tra suppor...

====================================================================================================
categorical_pair_interactions_validation.csv

,rule,feature_a,value_a,feature_b,value_b,support,support_rate,fraud_count,fraud_rate,global_fraud_rate,fraud_rate_diff,lift,order,strength,business_interpretation
0,payment_channel=ATM AND merchant_country=PH,payment_channel,ATM,merchant_country,PH,100,0.006667,8,0.080000,0.0252,0.054800,3.174603,2,STRONG,Một số tổ hợp kênh thanh toán và quốc gia merc...
1,payment_channel=API_SERVER AND merchant_countr...,payment_channel,API_SERVER,merchant_country,KR,107,0.007133,8,0.074766,0.0252,0.049566,2.966919,2,MEDIUM,Một số tổ hợp kênh thanh toán và quốc gia merc...
2,payment_channel=POS_TERMINAL AND merchant_coun...,payment_channel,POS_TERMINAL,merchant_country,AU,104,0.006933,7,0.067308,0.0252,0.042108,2.670940,2,MEDIUM,Một số tổ hợp kênh thanh toán và quốc gia merc...
3,cross_border=True AND merchant_country=PH,cross_border,True,merchant_country,PH,148,0.009867,9,0.060811,0.0252,0.035611,2.413127,2,MEDIUM,Giao dịch xuyên biên giới. Risk phụ thuộc vào ...
4,payment_channel=MOBILE_APP AND merchant_countr...,payment_channel,MOBILE_APP,merchant_country,GB,107,0.007133,6,0.056075,0.0252,0.030875,2.225189,2,MEDIUM,Một số tổ hợp kênh thanh toán và quốc gia merc...
5,payment_channel=MOBILE_APP AND merchant_countr...,payment_channel,MOBILE_APP,merchant_country,KR,110,0.007333,6,0.054545,0.0252,0.029345,2.164502,2,MEDIUM,Một số tổ hợp kênh thanh toán và quốc gia merc...
6,payment_channel=MOBILE_APP AND term_location=P...,payment_channel,MOBILE_APP,term_location,POS_TERMINAL,293,0.019533,15,0.051195,0.0252,0.025995,2.031529,2,MEDIUM,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
7,payment_channel=API_SERVER AND merchant_countr...,payment_channel,API_SERVER,merchant_country,ID,101,0.006733,5,0.049505,0.0252,0.024305,1.964482,2,WEAK,Một số tổ hợp kênh thanh toán và quốc gia merc...
8,payment_channel=SMART_WATCH AND merchant_count...,payment_channel,SMART_WATCH,merchant_country,ID,101,0.006733,5,0.049505,0.0252,0.024305,1.964482,2,WEAK,Một số tổ hợp kênh thanh toán và quốc gia merc...
9,payment_channel=MOBILE_APP AND merchant_countr...,payment_channel,MOBILE_APP,merchant_country,CN,103,0.006867,5,0.048544,0.0252,0.023344,1.926337,2,WEAK,Một số tổ hợp kênh thanh toán và quốc gia merc...
10,payment_channel=MOBILE_APP AND merchant_countr...,payment_channel,MOBILE_APP,merchant_country,IN,103,0.006867,5,0.048544,0.0252,0.023344,1.926337,2,WEAK,Một số tổ hợp kênh thanh toán và quốc gia merc...
11,payment_channel=SMART_WATCH AND merchant_count...,payment_channel,SMART_WATCH,merchant_country,BR,105,0.007000,5,0.047619,0.0252,0.022419,1.889645,2,WEAK,Một số tổ hợp kênh thanh toán và quốc gia merc...
12,payment_channel=IVR_PHONE AND merchant_country=AE,payment_channel,IVR_PHONE,merchant_country,AE,86,0.005733,4,0.046512,0.0252,0.021312,1.845700,2,WEAK,Một số tổ hợp kênh thanh toán và quốc gia merc...
13,payment_channel=API_SERVER AND merchant_countr...,payment_channel,API_SERVER,merchant_country,PH,108,0.007200,5,0.046296,0.0252,0.021096,1.837155,2,WEAK,Một số tổ hợp kênh thanh toán và quốc gia merc...
14,payment_channel=API_SERVER AND merchant_countr...,payment_channel,API_SERVER,merchant_country,VN,109,0.007267,5,0.045872,0.0252,0.020672,1.820300,2,WEAK,Một số tổ hợp kênh thanh toán và quốc gia merc...
15,cross_border=False AND merchant_country=KR,cross_border,False,merchant_country,KR,613,0.040867,28,0.045677,0.0252,0.020477,1.812579,2,WEAK,Giao dịch xuyên biên giới. Risk phụ thuộc vào ...
16,payment_channel=WEB_BROWSER AND merchant_count...,payment_channel,WEB_BROWSER,merchant_country,CA,110,0.007333,5,0.045455,0.0252,0.020255,1.803752,2,WEAK,Một số tổ hợp kênh thanh toán và quốc gia merc...
17,day_name=Wednesday AND payment_channel=MOBILE_APP,day_name,Wednesday,payment_channel,MOBILE_APP,288,0.019200,13,0.045139,0.0252,0.019939,1.791226,2,WEAK,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
18,card_entry_mode=TOKEN_IN_APP AND auth_result=B...,card_entry_mode,TOKEN_IN_APP,auth_result,BIOMETRIC_PASS,318,0.021200,14,0.044025,0.0252,0.018825,1.747030,2,WEAK,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
19,payment_channel=IVR_PHONE AND merchant_country=CA,payment_channel,IVR_PHONE,merchant_country,CA,114,0.007600,5,0.043860,0.0252,0.018660,1.740462,2,WEAK,Một số tổ hợp kênh thanh toán và quốc gia merc...
20,auth_result=BIOMETRIC_FAIL AND pin_verif_metho...,auth_result,BIOMETRIC_FAIL,pin_verif_method,SIGNATURE,457,0.030467,20,0.043764,0.0252,0.018564,1.736654,2,WEAK,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
21,time_period=late_evening AND payment_channel=S...,time_period,late_evening,payment_channel,SMART_WATCH,161,0.010733,7,0.043478,0.0252,0.018278,1.725328,2,WEAK,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
22,payment_channel=MOBILE_APP AND merchant_countr...,payment_channel,MOBILE_APP,merchant_country,DE,116,0.007733,5,0.043103,0.0252,0.017903,1.710454,2,WEAK,Một số tổ hợp kênh thanh toán và quốc gia merc...
23,card_entry_mode=MAGSTRIPE AND auth_result=BIOM...,card_entry_mode,MAGSTRIPE,auth_result,BIOMETRIC_FAIL,304,0.020267,13,0.042763,0.0252,0.017563,1.696951,2,WEAK,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
24,day_name=Thursday AND payment_channel=API_SERVER,day_name,Thursday,payment_channel,API_SERVER,305,0.020333,13,0.042623,0.0252,0.017423,1.691387,2,WEAK,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
25,payment_channel=ATM AND merchant_country=FR,payment_channel,ATM,merchant_country,FR,94,0.006267,4,0.042553,0.0252,0.017353,1.688619,2,WEAK,Một số tổ hợp kênh thanh toán và quốc gia merc...
26,payment_channel=ATM AND merchant_country=HK,payment_channel,ATM,merchant_country,HK,118,0.007867,5,0.042373,0.0252,0.017173,1.681464,2,WEAK,Một số tổ hợp kênh thanh toán và quốc gia merc...
27,payment_channel=POS_TERMINAL AND merchant_coun...,payment_channel,POS_TERMINAL,merchant_country,CA,118,0.007867,5,0.042373,0.0252,0.017173,1.681464,2,WEAK,Một số tổ hợp kênh thanh toán và quốc gia merc...
28,payment_channel=MOBILE_APP AND card_entry_mode...,payment_channel,MOBILE_APP,card_entry_mode,CONTACTLESS,333,0.022200,14,0.042042,0.0252,0.016842,1.668335,2,WEAK,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
29,payment_channel=POS_TERMINAL AND term_location...,payment_channel,POS_TERMINAL,term_location,ONLINE_PORTAL,310,0.020667,13,0.041935,0.0252,0.016735,1.664107,2,WEAK,Rule có tín hiệu thống kê. Cần kiểm tra suppor...

====================================================================================================
categorical_pair_stability.csv

,feature_a,value_a,feature_b,value_b,support_train,fraud_count_train,fraud_rate_train,global_fraud_rate_train,fraud_rate_diff_train,lift_train,support_valid,fraud_count_valid,fraud_rate_valid,global_fraud_rate_valid,fraud_rate_diff_valid,lift_valid,lift_diff_valid_train,lift_ratio_valid_train,fraud_rate_diff_valid_train
0,payment_channel,ATM,merchant_country,PH,476,12,0.025210,0.025471,-0.000261,0.989740,100,8,0.080000,0.0252,0.054800,3.174603,2.184863,3.207513,0.054790
1,payment_channel,API_SERVER,merchant_country,KR,527,6,0.011385,0.025471,-0.014086,0.446979,107,8,0.074766,0.0252,0.049566,2.966919,2.519940,6.637711,0.063381
2,payment_channel,POS_TERMINAL,merchant_country,AU,457,9,0.019694,0.025471,-0.005778,0.773166,104,7,0.067308,0.0252,0.042108,2.670940,1.897774,3.454547,0.047614
3,cross_border,True,merchant_country,PH,730,20,0.027397,0.025471,0.001926,1.075608,148,9,0.060811,0.0252,0.035611,2.413127,1.337520,2.243502,0.033414
4,payment_channel,MOBILE_APP,merchant_country,GB,503,11,0.021869,0.025471,-0.003603,0.858561,107,6,0.056075,0.0252,0.030875,2.225189,1.366628,2.591764,0.034206
5,payment_channel,MOBILE_APP,merchant_country,KR,505,12,0.023762,0.025471,-0.001709,0.932903,110,6,0.054545,0.0252,0.029345,2.164502,1.231599,2.320179,0.030783
6,payment_channel,MOBILE_APP,term_location,POS_TERMINAL,1417,35,0.024700,0.025471,-0.000771,0.969717,293,15,0.051195,0.0252,0.025995,2.031529,1.061813,2.094972,0.026494
7,payment_channel,SMART_WATCH,merchant_country,ID,476,13,0.027311,0.025471,0.001839,1.072218,101,5,0.049505,0.0252,0.024305,1.964482,0.892264,1.832167,0.022194
8,payment_channel,API_SERVER,merchant_country,ID,509,11,0.021611,0.025471,-0.003860,0.848441,101,5,0.049505,0.0252,0.024305,1.964482,1.116041,2.315402,0.027894
9,payment_channel,MOBILE_APP,merchant_country,IN,517,17,0.032882,0.025471,0.007411,1.290937,103,5,0.048544,0.0252,0.023344,1.926337,0.635400,1.492200,0.015662
10,payment_channel,MOBILE_APP,merchant_country,CN,453,8,0.017660,0.025471,-0.007811,0.693328,103,5,0.048544,0.0252,0.023344,1.926337,1.233009,2.778394,0.030884
11,payment_channel,SMART_WATCH,merchant_country,BR,529,14,0.026465,0.025471,0.000994,1.039008,105,5,0.047619,0.0252,0.022419,1.889645,0.850636,1.818700,0.021154
12,payment_channel,IVR_PHONE,merchant_country,AE,489,16,0.032720,0.025471,0.007248,1.284570,86,4,0.046512,0.0252,0.021312,1.845700,0.561129,1.436823,0.013792
13,payment_channel,API_SERVER,merchant_country,PH,466,14,0.030043,0.025471,0.004571,1.179475,108,5,0.046296,0.0252,0.021096,1.837155,0.657679,1.557603,0.016253
14,payment_channel,API_SERVER,merchant_country,VN,509,19,0.037328,0.025471,0.011857,1.465489,109,5,0.045872,0.0252,0.020672,1.820300,0.354811,1.242111,0.008543
15,cross_border,False,merchant_country,KR,2804,73,0.026034,0.025471,0.000563,1.022096,613,28,0.045677,0.0252,0.020477,1.812579,0.790484,1.773395,0.019643
16,payment_channel,WEB_BROWSER,merchant_country,CA,487,14,0.028747,0.025471,0.003276,1.128615,110,5,0.045455,0.0252,0.020255,1.803752,0.675137,1.598200,0.016707
17,day_name,Wednesday,payment_channel,MOBILE_APP,1432,40,0.027933,0.025471,0.002462,1.096639,288,13,0.045139,0.0252,0.019939,1.791226,0.694587,1.633378,0.017206
18,card_entry_mode,TOKEN_IN_APP,auth_result,BIOMETRIC_PASS,1432,44,0.030726,0.025471,0.005255,1.206303,318,14,0.044025,0.0252,0.018825,1.747030,0.540727,1.448252,0.013299
19,payment_channel,IVR_PHONE,merchant_country,CA,494,14,0.028340,0.025471,0.002869,1.112622,114,5,0.043860,0.0252,0.018660,1.740462,0.627840,1.564288,0.015520
20,auth_result,BIOMETRIC_FAIL,pin_verif_method,SIGNATURE,2189,52,0.023755,0.025471,-0.001716,0.932619,457,20,0.043764,0.0252,0.018564,1.736654,0.804035,1.862126,0.020009
21,time_period,late_evening,payment_channel,SMART_WATCH,887,35,0.039459,0.025471,0.013987,1.549142,161,7,0.043478,0.0252,0.018278,1.725328,0.176186,1.113731,0.004019
22,payment_channel,MOBILE_APP,merchant_country,DE,538,12,0.022305,0.025471,-0.003167,0.875680,116,5,0.043103,0.0252,0.017903,1.710454,0.834774,1.953286,0.020799
23,card_entry_mode,MAGSTRIPE,auth_result,BIOMETRIC_FAIL,1439,39,0.027102,0.025471,0.001631,1.064022,304,13,0.042763,0.0252,0.017563,1.696951,0.632929,1.594846,0.015661
24,day_name,Thursday,payment_channel,API_SERVER,1460,38,0.026027,0.025471,0.000556,1.021827,305,13,0.042623,0.0252,0.017423,1.691387,0.669560,1.655257,0.016596
25,payment_channel,ATM,merchant_country,FR,470,11,0.023404,0.025471,-0.002067,0.918843,94,4,0.042553,0.0252,0.017353,1.688619,0.769775,1.837765,0.019149
26,payment_channel,ATM,merchant_country,HK,511,16,0.031311,0.025471,0.005840,1.229266,118,5,0.042373,0.0252,0.017173,1.681464,0.452198,1.367860,0.011062
27,payment_channel,POS_TERMINAL,merchant_country,CA,421,11,0.026128,0.025471,0.000657,1.025787,118,5,0.042373,0.0252,0.017173,1.681464,0.655676,1.639193,0.016245
28,payment_channel,MOBILE_APP,card_entry_mode,CONTACTLESS,1696,50,0.029481,0.025471,0.004010,1.157420,333,14,0.042042,0.0252,0.016842,1.668335,0.510915,1.441426,0.012561
29,payment_channel,POS_TERMINAL,term_location,ONLINE_PORTAL,1368,35,0.025585,0.025471,0.000113,1.004451,310,13,0.041935,0.0252,0.016735,1.664107,0.659656,1.656733,0.016351

====================================================================================================
categorical_pattern_stability.csv

,feature,value,count_train,fraud_count_train,fraud_rate_train,global_fraud_rate_train,fraud_rate_diff_train,lift_train,count_valid,fraud_count_valid,fraud_rate_valid,global_fraud_rate_valid,fraud_rate_diff_valid,lift_valid,lift_diff_valid_train,lift_ratio_valid_train,fraud_rate_diff_valid_train
0,low_mcc_entropy_x_high_max_amount_30d,1,713,162,0.227209,0.025471,0.201738,8.920150,150,34,0.226667,0.0252,0.201467,8.994709,0.074559,1.008358,-0.000542
1,low_mcc_entropy_x_low_night_ratio,1,696,181,0.260057,0.025471,0.234586,10.209772,159,36,0.226415,0.0252,0.201215,8.984726,-1.225046,0.880012,-0.033642
2,low_night_ratio_x_high_max_amount_30d,1,728,124,0.170330,0.025471,0.144858,6.687087,157,32,0.203822,0.0252,0.178622,8.088161,1.401074,1.209519,0.033492
3,low_mcc_entropy_x_low_spending_trend,1,733,175,0.238745,0.025471,0.213273,9.373046,130,26,0.200000,0.0252,0.174800,7.936508,-1.436539,0.846737,-0.038745
4,night_unusual_group,very_high,2339,167,0.071398,0.025471,0.045927,2.803064,496,41,0.082661,0.0252,0.057461,3.280210,0.477146,1.170223,0.011263
5,low_mcc_entropy_x_card_not_present,1,4570,419,0.091685,0.025471,0.066213,3.599519,969,70,0.072239,0.0252,0.047039,2.866644,-0.732876,0.796396,-0.019445
6,night_ratio_group,very_low,6924,503,0.072646,0.025471,0.047174,2.852053,1503,108,0.071856,0.0252,0.046656,2.851440,-0.000613,0.999785,-0.000790
7,cross_border_x_low_country_diversity,1,1692,86,0.050827,0.025471,0.025356,1.995468,400,26,0.065000,0.0252,0.039800,2.579365,0.583897,1.292612,0.014173
8,night_ratio_group,low,14006,622,0.044410,0.025471,0.018938,1.743504,3085,133,0.043112,0.0252,0.017912,1.710787,-0.032717,0.981235,-0.001298
9,credit_util_risk_group,low,10611,381,0.035906,0.025471,0.010435,1.409663,2284,97,0.042469,0.0252,0.017269,1.685292,0.275629,1.195528,0.006563
10,night_unusual_group,high,7144,294,0.041153,0.025471,0.015682,1.615670,1406,58,0.041252,0.0252,0.016052,1.636975,0.021306,1.013187,0.000098
11,currency,KRW,1981,38,0.019182,0.025471,-0.006289,0.753088,444,18,0.040541,0.0252,0.015341,1.608752,0.855663,2.136206,0.021358
12,merchant_country,PH,3444,99,0.028746,0.025471,0.003274,1.128545,749,29,0.038718,0.0252,0.013518,1.536440,0.407895,1.361435,0.009973
13,merchant_country,KR,3519,79,0.022450,0.025471,-0.003022,0.881362,781,30,0.038412,0.0252,0.013212,1.524297,0.642935,1.729478,0.015963
14,amount_to_max_group,below_half_max,21845,777,0.035569,0.025471,0.010097,1.396419,4602,174,0.037810,0.0252,0.012610,1.500383,0.103964,1.074451,0.002241
15,decline_rate_risk_group,low,16873,630,0.037338,0.025471,0.011866,1.465868,3634,136,0.037424,0.0252,0.012224,1.485092,0.019224,1.013114,0.000087
16,currency,GBP,5395,119,0.022057,0.025471,-0.003414,0.865969,1074,39,0.036313,0.0252,0.011113,1.440986,0.575017,1.664016,0.014255
17,message_type,0100-AuthReq,8902,212,0.023815,0.025471,-0.001657,0.934964,1962,69,0.035168,0.0252,0.009968,1.395563,0.460599,1.492638,0.011353
18,currency,SGD,1978,56,0.028311,0.025471,0.002840,1.111497,460,16,0.034783,0.0252,0.009583,1.380262,0.268765,1.241804,0.006471
19,auth_result,AVS_FAIL,8905,211,0.023695,0.025471,-0.001777,0.930240,1900,65,0.034211,0.0252,0.009011,1.357561,0.427320,1.459365,0.010516
20,time_period,late_evening,5931,168,0.028326,0.025471,0.002854,1.112060,1179,39,0.033079,0.0252,0.007879,1.312654,0.200594,1.180381,0.004753
21,term_location,POS_TERMINAL,10180,247,0.024263,0.025471,-0.001208,0.952568,2189,72,0.032892,0.0252,0.007692,1.305227,0.352660,1.370220,0.008628
22,merchant_country,ID,3468,83,0.023933,0.025471,-0.001538,0.939606,736,24,0.032609,0.0252,0.007409,1.293996,0.354390,1.377169,0.008676
23,txn_count_7d_group,11_20,8184,187,0.022849,0.025471,-0.002622,0.897062,1743,56,0.032129,0.0252,0.006929,1.274941,0.377879,1.421240,0.009279
24,day_name,Wednesday,9873,238,0.024106,0.025471,-0.001365,0.946400,2199,70,0.031833,0.0252,0.006633,1.263200,0.316801,1.334743,0.007727
25,amount_to_max_group,near_max,19962,693,0.034716,0.025471,0.009245,1.362937,4312,136,0.031540,0.0252,0.006340,1.251583,-0.111354,0.918298,-0.003176
26,merchant_country,VN,3516,96,0.027304,0.025471,0.001832,1.071937,769,24,0.031209,0.0252,0.006009,1.238467,0.166530,1.155355,0.003906
27,txn_velocity_group,high,2742,76,0.027717,0.025471,0.002246,1.088160,578,18,0.031142,0.0252,0.005942,1.235788,0.147628,1.135668,0.003425
28,currency,THB,2754,65,0.023602,0.025471,-0.001869,0.926608,597,18,0.030151,0.0252,0.004951,1.196458,0.269850,1.291224,0.006549
29,credit_util_risk_group,medium,10496,343,0.032679,0.025471,0.007208,1.282971,2223,67,0.030139,0.0252,0.004939,1.196010,-0.086961,0.932219,-0.002540

====================================================================================================
feature_recommendations_train.csv

,rule,support,support_rate,fraud_count,fraud_rate,global_fraud_rate,fraud_rate_diff,lift,order,strength,business_interpretation,feature_recommendation
0,low_mcc_entropy AND low_night_ratio AND high_m...,74,0.001057,39,0.527027,0.025471,0.501556,20.690910,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...,Nên tạo binary interaction feature cho Logisti...
1,low_mcc_entropy AND low_night_ratio AND card_n...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...,Nên tạo binary interaction feature cho Logisti...
2,low_mcc_entropy AND low_night_ratio,696,0.009943,181,0.260057,0.025471,0.234586,10.209772,2,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...,Nên tạo binary interaction feature cho Logisti...
3,low_mcc_entropy AND low_spending_trend,733,0.010471,175,0.238745,0.025471,0.213273,9.373046,2,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...,Nên tạo binary interaction feature cho Logisti...
4,low_mcc_entropy AND high_max_amount_30d,713,0.010186,162,0.227209,0.025471,0.201738,8.920150,2,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...,Nên tạo binary interaction feature cho Logisti...
5,low_night_ratio AND high_max_amount_30d,728,0.010400,124,0.170330,0.025471,0.144858,6.687087,2,VERY_STRONG,Rule có tín hiệu thống kê. Cần kiểm tra suppor...,Nên tạo binary interaction feature cho Logisti...
6,low_mcc_entropy AND card_not_present,4570,0.065286,419,0.091685,0.025471,0.066213,3.599519,2,STRONG,Giao dịch không có thẻ vật lý. Với fraud onlin...,Nên tạo binary interaction feature cho Logisti...
7,low_night_ratio AND night_transaction,2401,0.034300,171,0.071220,0.025471,0.045749,2.796087,2,MEDIUM,Rule có tín hiệu thống kê. Cần kiểm tra suppor...,Nên tạo binary interaction feature cho Logisti...

====================================================================================================
numeric_bin_fraud_rate_train.csv

            feature                       bin  count  fraud_count  fraud_rate  global_fraud_rate  fraud_rate_diff      lift  min_value  max_value     mean_value
0            amount    (20064.603, 39866.496]   7000          191    0.027286           0.025471         0.001814  1.071228   20064.74   39865.56   29960.735031
1            amount     (59660.565, 79869.11]   7000          190    0.027143           0.025471         0.001671  1.065620   59660.73   79863.89   69770.704419
2            amount     (79869.11, 100132.98]   7000          184    0.026286           0.025471         0.000814  1.031969   79872.59  100129.94   90005.541841
3            amount  (140466.319, 160364.184]   7000          182    0.026000           0.025471         0.000529  1.020752  140468.44  160363.04  150426.793346
4            amount   (120348.22, 140466.319]   7000          178    0.025429           0.025471        -0.000043  0.998317  120350.65  140465.41  130398.787450
5            amount         (-inf, 20064.603]   7000          176    0.025143           0.025471        -0.000329  0.987100       1.43   20063.37   10063.440307
6            amount    (100132.98, 120348.22]   7000          175    0.025000           0.025471        -0.000471  0.981492  100136.02  120346.60  110281.907807
7            amount         (180212.031, inf]   7000          173    0.024714           0.025471        -0.000757  0.970275  180213.12  199996.14  190063.088561
8            amount    (39866.496, 59660.565]   7000          170    0.024286           0.025471        -0.001186  0.953449   39866.73   59660.18   49785.069324
9            amount  (160364.184, 180212.031]   7000          164    0.023429           0.025471        -0.002043  0.919798  160368.76  180211.91  170297.901890
10  mean_amount_30d              (11.16, inf]   6992          221    0.031608           0.025471         0.006136  1.240902      11.17      97.99      15.353262
11  mean_amount_30d               (7.84, 9.0]   6984          211    0.030212           0.025471         0.004740  1.186110       7.85       9.00       8.377496
12  mean_amount_30d              (9.0, 11.16]   6973          205    0.029399           0.025471         0.003928  1.154200       9.01      11.16       9.939908
13  mean_amount_30d              (6.55, 7.09]   6957          182    0.026161           0.025471         0.000689  1.027061       6.56       7.09       6.812086
14  mean_amount_30d              (7.09, 7.84]   6998          178    0.025436           0.025471        -0.000036  0.998603       7.10       7.84       7.449661
15  mean_amount_30d              (5.22, 5.47]   7031          172    0.024463           0.025471        -0.001008  0.960413       5.23       5.47       5.345662
16  mean_amount_30d              (6.12, 6.55]   7022          169    0.024067           0.025471        -0.001404  0.944871       6.13       6.55       6.332485
17  mean_amount_30d              (5.77, 6.12]   6925          158    0.022816           0.025471        -0.002656  0.895744       5.78       6.12       5.945255
18  mean_amount_30d              (5.47, 5.77]   7025          144    0.020498           0.025471        -0.004973  0.804753       5.48       5.77       5.620184
19  mean_amount_30d              (-inf, 5.22]   7093          143    0.020161           0.025471        -0.005311  0.791503       5.00       5.22       5.110244
20   std_amount_30d              (-inf, 1.12]   7397          389    0.052589           0.025471         0.027117  2.064623       1.00       1.12       1.061372
21   std_amount_30d              (1.12, 1.25]   6710          292    0.043517           0.025471         0.018046  1.708469       1.13       1.25       1.188274
22   std_amount_30d              (1.25, 1.41]   7020          253    0.036040           0.025471         0.010568  1.414914       1.26       1.41       1.332168
23   std_amount_30d               (1.41, 1.6]   7108          216    0.030388           0.025471         0.004917  1.193035       1.42       1.60       1.506946
24   std_amount_30d               (1.6, 1.83]   6880          161    0.023401           0.025471        -0.002070  0.918722       1.61       1.83       1.716138
25   std_amount_30d              (1.83, 2.13]   7000          118    0.016857           0.025471        -0.008614  0.661806       1.84       2.13       1.977707
26   std_amount_30d              (2.13, 2.54]   6935          112    0.016150           0.025471        -0.009321  0.634042       2.14       2.54       2.328121
27   std_amount_30d              (2.54, 3.18]   7038           86    0.012219           0.025471        -0.013252  0.479729       2.55       3.18       2.836380
28   std_amount_30d              (3.18, 4.41]   6938           80    0.011531           0.025471        -0.013941  0.452692       3.19       4.41       3.710182
29   std_amount_30d               (4.41, inf]   6974           76    0.010898           0.025471        -0.014574  0.427837       4.42      42.97       6.862429

====================================================================================================
numeric_bin_fraud_rate_validation.csv

            feature                       bin  count  fraud_count  fraud_rate  global_fraud_rate  fraud_rate_diff      lift  min_value  max_value     mean_value
0            amount         (-inf, 20064.603]   1481           54    0.036462             0.0252         0.011262  1.446899       4.79   20056.77    9979.176313
1            amount     (59660.565, 79869.11]   1509           43    0.028496             0.0252         0.003296  1.130781   59679.11   79803.96   69694.105547
2            amount   (120348.22, 140466.319]   1482           41    0.027665             0.0252         0.002465  1.097830  120357.78  140444.24  130504.847058
3            amount  (140466.319, 160364.184]   1594           41    0.025721             0.0252         0.000521  1.020693  140470.82  160362.44  150359.854931
4            amount    (39866.496, 59660.565]   1454           35    0.024072             0.0252        -0.001128  0.955219   39868.23   59659.05   49807.375275
5            amount    (100132.98, 120348.22]   1509           36    0.023857             0.0252        -0.001343  0.946701  100170.56  120331.69  110385.095666
6            amount     (79869.11, 100132.98]   1469           34    0.023145             0.0252        -0.002055  0.918452   79873.74  100127.15   89920.025446
7            amount  (160364.184, 180212.031]   1497           34    0.022712             0.0252        -0.002488  0.901273  160387.44  180210.65  170085.916640
8            amount    (20064.603, 39866.496]   1512           31    0.020503             0.0252        -0.004697  0.813597   20110.61   39851.83   29644.150549
9            amount         (180212.031, inf]   1493           29    0.019424             0.0252        -0.005776  0.770793  180229.85  199999.75  190463.528091
10  mean_amount_30d              (7.09, 7.84]   1485           52    0.035017             0.0252         0.009817  1.389557       7.10       7.84       7.456936
11  mean_amount_30d              (11.16, inf]   1509           47    0.031146             0.0252         0.005946  1.235970      11.17      66.62      15.153294
12  mean_amount_30d              (6.12, 6.55]   1443           39    0.027027             0.0252         0.001827  1.072501       6.13       6.55       6.332259
13  mean_amount_30d               (7.84, 9.0]   1458           37    0.025377             0.0252         0.000177  1.007033       7.85       9.00       8.385514
14  mean_amount_30d              (5.77, 6.12]   1509           38    0.025182             0.0252        -0.000018  0.999295       5.78       6.12       5.943347
15  mean_amount_30d              (5.47, 5.77]   1566           38    0.024266             0.0252        -0.000934  0.962922       5.48       5.77       5.621373
16  mean_amount_30d              (-inf, 5.22]   1513           35    0.023133             0.0252        -0.002067  0.917970       5.00       5.22       5.108348
17  mean_amount_30d              (9.0, 11.16]   1458           31    0.021262             0.0252        -0.003938  0.843730       9.01      11.16       9.928182
18  mean_amount_30d              (6.55, 7.09]   1550           32    0.020645             0.0252        -0.004555  0.819252       6.56       7.09       6.812671
19  mean_amount_30d              (5.22, 5.47]   1509           29    0.019218             0.0252        -0.005982  0.762620       5.23       5.47       5.347528
20   std_amount_30d              (1.12, 1.25]   1392           73    0.052443             0.0252         0.027243  2.081053       1.13       1.25       1.189382
21   std_amount_30d              (-inf, 1.12]   1560           80    0.051282             0.0252         0.026082  2.035002       1.00       1.12       1.059583
22   std_amount_30d              (1.25, 1.41]   1538           51    0.033160             0.0252         0.007960  1.315871       1.26       1.41       1.332620
23   std_amount_30d               (1.41, 1.6]   1527           47    0.030779             0.0252         0.005579  1.221401       1.42       1.60       1.509194
24   std_amount_30d               (1.6, 1.83]   1501           41    0.027315             0.0252         0.002115  1.083933       1.61       1.83       1.713817
25   std_amount_30d              (1.83, 2.13]   1451           26    0.017919             0.0252        -0.007281  0.711059       1.84       2.13       1.982550
26   std_amount_30d              (2.54, 3.18]   1486           21    0.014132             0.0252        -0.011068  0.560790       2.55       3.18       2.846575
27   std_amount_30d              (2.13, 2.54]   1522           20    0.013141             0.0252        -0.012059  0.521453       2.14       2.54       2.331524
28   std_amount_30d              (3.18, 4.41]   1462           10    0.006840             0.0252        -0.018360  0.271426       3.19       4.41       3.713358
29   std_amount_30d               (4.41, inf]   1561            9    0.005766             0.0252        -0.019434  0.228791       4.42      42.43       6.870685

====================================================================================================
numeric_pattern_stability.csv

,feature,bin,count_train,fraud_count_train,fraud_rate_train,global_fraud_rate_train,fraud_rate_diff_train,lift_train,count_valid,fraud_count_valid,fraud_rate_valid,global_fraud_rate_valid,fraud_rate_diff_valid,lift_valid,lift_diff_valid_train,lift_ratio_valid_train,fraud_rate_diff_valid_train
0,max_amount_30d,"(225176.777, inf]",7000,439,0.062714,0.025471,0.037243,2.462142,1444,115,0.079640,0.0252,0.054440,3.160313,0.698171,1.283562,0.016926
1,mcc_entropy_30d,"(-inf, 0.393]",7009,625,0.089171,0.025471,0.063700,3.500827,1525,112,0.073443,0.0252,0.048243,2.914390,-0.586437,0.832486,-0.015728
2,night_ratio_30d,"(-inf, 0.101]",7038,511,0.072606,0.025471,0.047134,2.850482,1531,111,0.072502,0.0252,0.047302,2.877049,0.026567,1.009320,-0.000104
3,spending_trend,"(-inf, 0.584]",7002,463,0.066124,0.025471,0.040653,2.596005,1400,89,0.063571,0.0252,0.038371,2.522676,-0.073330,0.971753,-0.002553
4,distinct_countries_30d,"(-inf, 3.0]",8464,525,0.062027,0.025471,0.036556,2.435176,1842,114,0.061889,0.0252,0.036689,2.455923,0.020747,1.008520,-0.000138
5,mcc_entropy_30d,"(0.393, 0.788]",6992,413,0.059068,0.025471,0.033596,2.318971,1405,85,0.060498,0.0252,0.035298,2.400723,0.081752,1.035254,0.001431
6,night_unusual_score,"(0.705, inf]",6991,381,0.054499,0.025471,0.029027,2.139599,1410,84,0.059574,0.0252,0.034374,2.364066,0.224467,1.104911,0.005076
7,spending_trend,"(0.584, 1.073]",7008,331,0.047232,0.025471,0.021760,1.854303,1522,81,0.053219,0.0252,0.028019,2.111883,0.257580,1.138910,0.005988
8,std_amount_30d,"(1.12, 1.25]",6710,292,0.043517,0.025471,0.018046,1.708469,1392,73,0.052443,0.0252,0.027243,2.081053,0.372584,1.218081,0.008925
9,std_amount_30d,"(-inf, 1.12]",7397,389,0.052589,0.025471,0.027117,2.064623,1560,80,0.051282,0.0252,0.026082,2.035002,-0.029621,0.985653,-0.001307
10,night_ratio_30d,"(0.101, 0.201]",6999,362,0.051722,0.025471,0.026250,2.030576,1502,71,0.047270,0.0252,0.022070,1.875806,-0.154770,0.923780,-0.004451
11,distinct_countries_30d,"(3.0, 6.0]",8280,363,0.043841,0.025471,0.018369,1.721167,1860,87,0.046774,0.0252,0.021574,1.856119,0.134952,1.078407,0.002934
12,mcc_entropy_30d,"(0.788, 1.187]",7012,258,0.036794,0.025471,0.011323,1.444523,1494,67,0.044846,0.0252,0.019646,1.779605,0.335082,1.231967,0.008052
13,amount_to_max_30d,"(-inf, 0.16]",7000,255,0.036429,0.025471,0.010957,1.430174,1499,65,0.043362,0.0252,0.018162,1.720724,0.290550,1.203157,0.006934
14,credit_util_today,"(0.197, 0.397]",7012,242,0.034512,0.025471,0.009041,1.354940,1512,64,0.042328,0.0252,0.017128,1.679684,0.324744,1.239674,0.007816
15,device_diversity_30d,"(5.0, 8.0]",5370,203,0.037803,0.025471,0.012331,1.484118,1097,46,0.041933,0.0252,0.016733,1.663990,0.179872,1.121198,0.004130
16,device_diversity_30d,"(-inf, 5.0]",8715,325,0.037292,0.025471,0.011821,1.464073,1947,81,0.041602,0.0252,0.016402,1.650891,0.186819,1.127602,0.004310
17,credit_util_today,"(-inf, 0.197]",7014,258,0.036784,0.025471,0.011312,1.444111,1476,61,0.041328,0.0252,0.016128,1.639997,0.195885,1.135644,0.004544
18,amount_to_max_30d,"(0.482, 0.642]",7000,252,0.036000,0.025471,0.010529,1.413348,1484,61,0.041105,0.0252,0.015905,1.631156,0.217807,1.154107,0.005105
19,decline_rate_30d,"(-inf, 0.067]",7161,309,0.043150,0.025471,0.017679,1.694071,1614,65,0.040273,0.0252,0.015073,1.598120,-0.095951,0.943361,-0.002878
20,amount_to_max_30d,"(0.317, 0.482]",7000,236,0.033714,0.025471,0.008243,1.323612,1471,58,0.039429,0.0252,0.014229,1.564641,0.241029,1.182100,0.005715
21,night_ratio_30d,"(0.201, 0.301]",7010,259,0.036947,0.025471,0.011476,1.450536,1582,62,0.039191,0.0252,0.013991,1.555194,0.104659,1.072152,0.002244
22,decline_rate_30d,"(0.067, 0.092]",7116,239,0.033586,0.025471,0.008115,1.318587,1482,56,0.037787,0.0252,0.012587,1.499475,0.180889,1.137184,0.004200
23,distinct_countries_30d,"(6.0, 8.0]",5673,192,0.033845,0.025471,0.008373,1.328725,1126,42,0.037300,0.0252,0.012100,1.480166,0.151441,1.113974,0.003456
24,chargebacks_365d,"(2.0, inf]",5436,165,0.030353,0.025471,0.004882,1.191657,1206,44,0.036484,0.0252,0.011284,1.447788,0.256131,1.214937,0.006131
25,amount,"(-inf, 20064.603]",7000,176,0.025143,0.025471,-0.000329,0.987100,1481,54,0.036462,0.0252,0.011262,1.446899,0.459798,1.465807,0.011319
26,max_amount_30d,"(200126.978, 225176.777]",7000,370,0.052857,0.025471,0.027386,2.075154,1517,54,0.035597,0.0252,0.010397,1.412562,-0.662592,0.680702,-0.017261
27,mean_amount_30d,"(7.09, 7.84]",6998,178,0.025436,0.025471,-0.000036,0.998603,1485,52,0.035017,0.0252,0.009817,1.389557,0.390954,1.391501,0.009581
28,txn_count_ratio_7d_30d,"(0.112, 0.15]",7000,198,0.028286,0.025471,0.002814,1.110488,1499,52,0.034690,0.0252,0.009490,1.376579,0.266091,1.239616,0.006404
29,amount_to_mean_30d,"(-inf, 2335.611]",7000,180,0.025714,0.025471,0.000243,1.009534,1507,52,0.034506,0.0252,0.009306,1.369271,0.359737,1.356339,0.008791

====================================================================================================
priority_business_interactions_train.csv

,rule,support,support_rate,fraud_count,fraud_rate,global_fraud_rate,fraud_rate_diff,lift,order,strength,business_interpretation
0,low_mcc_entropy AND low_night_ratio AND high_m...,74,0.001057,39,0.527027,0.025471,0.501556,20.690910,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
1,low_mcc_entropy AND low_night_ratio AND card_n...,479,0.006843,128,0.267223,0.025471,0.241752,10.491103,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
2,low_mcc_entropy AND low_night_ratio,696,0.009943,181,0.260057,0.025471,0.234586,10.209772,2,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
3,low_mcc_entropy AND low_spending_trend,733,0.010471,175,0.238745,0.025471,0.213273,9.373046,2,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...
4,low_mcc_entropy AND high_max_amount_30d,713,0.010186,162,0.227209,0.025471,0.201738,8.920150,2,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...
5,low_night_ratio AND high_max_amount_30d,728,0.010400,124,0.170330,0.025471,0.144858,6.687087,2,VERY_STRONG,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
6,low_mcc_entropy AND card_not_present,4570,0.065286,419,0.091685,0.025471,0.066213,3.599519,2,STRONG,Giao dịch không có thẻ vật lý. Với fraud onlin...
7,low_night_ratio AND night_transaction,2401,0.034300,171,0.071220,0.025471,0.045749,2.796087,2,MEDIUM,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
8,cross_border AND low_country_diversity,1692,0.024171,86,0.050827,0.025471,0.025356,1.995468,2,WEAK,Giao dịch xuyên biên giới trong khi user có lị...
9,high_ip_score AND card_not_present,4474,0.063914,113,0.025257,0.025471,-0.000214,0.991583,2,LOW_SIGNAL,Giao dịch không có thẻ vật lý. Với fraud onlin...
10,high_device_diversity AND card_not_present,5657,0.080814,78,0.013788,0.025471,-0.011683,0.541321,2,LOW_SIGNAL,Giao dịch không có thẻ vật lý. Với fraud onlin...
11,high_decline_rate AND card_not_present,4577,0.065386,62,0.013546,0.025471,-0.011925,0.531811,2,LOW_SIGNAL,Giao dịch không có thẻ vật lý. Với fraud onlin...

====================================================================================================
priority_business_interactions_validation.csv

,rule,support,support_rate,fraud_count,fraud_rate,global_fraud_rate,fraud_rate_diff,lift,order,strength,business_interpretation
0,low_mcc_entropy AND low_night_ratio AND card_n...,94,0.006267,25,0.265957,0.0252,0.240757,10.553867,3,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
1,low_mcc_entropy AND high_max_amount_30d,150,0.010000,34,0.226667,0.0252,0.201467,8.994709,2,VERY_STRONG,User có hành vi ngành hàng hẹp nhưng có lịch s...
2,low_mcc_entropy AND low_night_ratio,159,0.010600,36,0.226415,0.0252,0.201215,8.984726,2,VERY_STRONG,User có lịch sử ngành hàng ít đa dạng và ít gi...
3,low_night_ratio AND high_max_amount_30d,157,0.010467,32,0.203822,0.0252,0.178622,8.088161,2,VERY_STRONG,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
4,low_mcc_entropy AND low_spending_trend,130,0.008667,26,0.200000,0.0252,0.174800,7.936508,2,VERY_STRONG,User có ngành hàng giao dịch hẹp và xu hướng c...
5,low_night_ratio AND night_transaction,509,0.033933,41,0.080550,0.0252,0.055350,3.196432,2,STRONG,Rule có tín hiệu thống kê. Cần kiểm tra suppor...
6,low_mcc_entropy AND card_not_present,969,0.064600,70,0.072239,0.0252,0.047039,2.866644,2,MEDIUM,Giao dịch không có thẻ vật lý. Với fraud onlin...
7,cross_border AND low_country_diversity,400,0.026667,26,0.065000,0.0252,0.039800,2.579365,2,MEDIUM,Giao dịch xuyên biên giới trong khi user có lị...
8,high_ip_score AND card_not_present,982,0.065467,28,0.028513,0.0252,0.003313,1.131478,2,LOW_SIGNAL,Giao dịch không có thẻ vật lý. Với fraud onlin...
9,high_device_diversity AND card_not_present,1218,0.081200,20,0.016420,0.0252,-0.008780,0.651602,2,LOW_SIGNAL,Giao dịch không có thẻ vật lý. Với fraud onlin...
10,high_decline_rate AND card_not_present,983,0.065533,15,0.015259,0.0252,-0.009941,0.605532,2,LOW_SIGNAL,Giao dịch không có thẻ vật lý. Với fraud onlin...

====================================================================================================
priority_interaction_stability.csv

,rule,support_train,fraud_count_train,fraud_rate_train,global_fraud_rate_train,fraud_rate_diff_train,lift_train,support_valid,fraud_count_valid,fraud_rate_valid,global_fraud_rate_valid,fraud_rate_diff_valid,lift_valid,lift_diff_valid_train,lift_ratio_valid_train,fraud_rate_diff_valid_train
0,low_mcc_entropy AND low_night_ratio AND card_n...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
1,low_mcc_entropy AND high_max_amount_30d,713,162,0.227209,0.025471,0.201738,8.920150,150,34,0.226667,0.0252,0.201467,8.994709,0.074559,1.008358,-0.000542
2,low_mcc_entropy AND low_night_ratio,696,181,0.260057,0.025471,0.234586,10.209772,159,36,0.226415,0.0252,0.201215,8.984726,-1.225046,0.880012,-0.033642
3,low_night_ratio AND high_max_amount_30d,728,124,0.170330,0.025471,0.144858,6.687087,157,32,0.203822,0.0252,0.178622,8.088161,1.401074,1.209519,0.033492
4,low_mcc_entropy AND low_spending_trend,733,175,0.238745,0.025471,0.213273,9.373046,130,26,0.200000,0.0252,0.174800,7.936508,-1.436539,0.846737,-0.038745
5,low_night_ratio AND night_transaction,2401,171,0.071220,0.025471,0.045749,2.796087,509,41,0.080550,0.0252,0.055350,3.196432,0.400346,1.143181,0.009330
6,low_mcc_entropy AND card_not_present,4570,419,0.091685,0.025471,0.066213,3.599519,969,70,0.072239,0.0252,0.047039,2.866644,-0.732876,0.796396,-0.019445
7,cross_border AND low_country_diversity,1692,86,0.050827,0.025471,0.025356,1.995468,400,26,0.065000,0.0252,0.039800,2.579365,0.583897,1.292612,0.014173
8,high_ip_score AND card_not_present,4474,113,0.025257,0.025471,-0.000214,0.991583,982,28,0.028513,0.0252,0.003313,1.131478,0.139895,1.141082,0.003256
9,high_device_diversity AND card_not_present,5657,78,0.013788,0.025471,-0.011683,0.541321,1218,20,0.016420,0.0252,-0.008780,0.651602,0.110280,1.203724,0.002632
10,high_decline_rate AND card_not_present,4577,62,0.013546,0.025471,-0.011925,0.531811,983,15,0.015259,0.0252,-0.009941,0.605532,0.073721,1.138622,0.001713

====================================================================================================
segment_stability.csv

,segment_name,support_train,fraud_count_train,fraud_rate_train,global_fraud_rate_train,fraud_rate_diff_train,lift_train,support_valid,fraud_count_valid,fraud_rate_valid,global_fraud_rate_valid,fraud_rate_diff_valid,lift_valid,lift_diff_valid_train,lift_ratio_valid_train,fraud_rate_diff_valid_train
0,night_unusual,2401,171,0.071220,0.025471,0.045749,2.796087,496,41,0.082661,0.0252,0.057461,3.280210,0.484123,1.173143,0.011441
1,very_low_mcc_entropy,3510,339,0.096581,0.025471,0.071110,3.791746,750,61,0.081333,0.0252,0.056133,3.227513,-0.564233,0.851194,-0.015248
2,high_max_amount_30d,7000,439,0.062714,0.025471,0.037243,2.462142,1500,116,0.077333,0.0252,0.052133,3.068783,0.606641,1.246387,0.014619
3,low_night_ratio,7038,511,0.072606,0.025471,0.047134,2.850482,1500,110,0.073333,0.0252,0.048133,2.910053,0.059571,1.020898,0.000727
4,low_mcc_entropy,7009,625,0.089171,0.025471,0.063700,3.500827,1503,110,0.073187,0.0252,0.047987,2.904244,-0.596583,0.829588,-0.015984
5,low_country_diversity,8464,525,0.062027,0.025471,0.036556,2.435176,1842,114,0.061889,0.0252,0.036689,2.455923,0.020747,1.008520,-0.000138
6,has_chargeback_history,10439,306,0.029313,0.025471,0.003842,1.150825,2323,69,0.029703,0.0252,0.004503,1.178689,0.027864,1.024213,0.000390
7,night_transaction,23339,611,0.026179,0.025471,0.000708,1.027793,4749,132,0.027795,0.0252,0.002595,1.102989,0.075196,1.073163,0.001616
8,card_not_present,45672,1201,0.026296,0.025471,0.000825,1.032380,9663,245,0.025354,0.0252,0.000154,1.006129,-0.026251,0.974572,-0.000942
9,high_ip_score,7001,172,0.024568,0.025471,-0.000904,0.964529,1500,38,0.025333,0.0252,0.000133,1.005291,0.040763,1.042262,0.000765
10,tokenised_transaction,31516,784,0.024876,0.025471,-0.000595,0.976634,6736,162,0.024050,0.0252,-0.001150,0.954360,-0.022273,0.977194,-0.000826
11,cross_border,13963,280,0.020053,0.025471,-0.005418,0.787274,3035,63,0.020758,0.0252,-0.004442,0.823723,0.036449,1.046298,0.000705
12,high_amount_to_mean,7000,147,0.021000,0.025471,-0.004471,0.824453,1500,30,0.020000,0.0252,-0.005200,0.793651,-0.030802,0.962639,-0.001000
13,high_current_amount,7000,173,0.024714,0.025471,-0.000757,0.970275,1500,29,0.019333,0.0252,-0.005867,0.767196,-0.203079,0.790699,-0.005381
14,high_device_diversity,8633,125,0.014479,0.025471,-0.010992,0.568454,1897,34,0.017923,0.0252,-0.007277,0.711232,0.142778,1.251169,0.003444
15,high_decline_rate,7070,97,0.013720,0.025471,-0.011751,0.538641,1519,21,0.013825,0.0252,-0.011375,0.548607,0.009966,1.018502,0.000105
16,high_amount_to_max,7000,46,0.006571,0.025471,-0.018900,0.257992,1500,13,0.008667,0.0252,-0.016533,0.343915,0.085923,1.333046,0.002095
17,low_spending_trend,0,0,0.000000,0.025471,-0.025471,0.000000,0,0,0.000000,0.0252,-0.025200,0.000000,0.000000,0.000000,0.000000

====================================================================================================
split_summary.csv

        split   rows  fraud_count  non_fraud_count  fraud_rate           start_time             end_time split_strategy
0       train  70000         1783            68217    0.025471  2025-03-07 07:19:19  2025-05-09 08:45:13           time
1  validation  15000          378            14622    0.025200  2025-05-09 08:46:31  2025-05-22 21:09:42           time
2        test  15000          388            14612    0.025867  2025-05-22 21:09:58  2025-06-05 07:17:23           time

====================================================================================================
stable_boolean_interactions.csv

,rule,support_train,fraud_count_train,fraud_rate_train,global_fraud_rate_train,fraud_rate_diff_train,lift_train,support_valid,fraud_count_valid,fraud_rate_valid,global_fraud_rate_valid,fraud_rate_diff_valid,lift_valid,lift_diff_valid_train,lift_ratio_valid_train,fraud_rate_diff_valid_train
0,high_max_amount_30d_flag AND low_country_diver...,354,58,0.163842,0.025471,0.138370,6.432376,83,23,0.277108,0.0252,0.251908,10.996366,4.563990,1.709534,0.113267
1,low_night_ratio_flag AND low_mcc_entropy_x_car...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
2,card_not_present_flag AND low_mcc_entropy_x_lo...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
3,low_mcc_entropy_x_low_night_ratio AND low_mcc_...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
4,low_mcc_entropy_flag AND low_night_ratio_flag ...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
5,low_mcc_entropy_flag AND low_night_ratio_flag ...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
6,low_mcc_entropy_flag AND card_not_present_flag...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
7,low_mcc_entropy_flag AND low_mcc_entropy_x_low...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
8,low_night_ratio_flag AND card_not_present_flag...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
9,low_night_ratio_flag AND card_not_present_flag...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
10,low_night_ratio_flag AND low_mcc_entropy_x_low...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
11,card_not_present_flag AND low_mcc_entropy_x_lo...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
12,high_max_amount_30d_flag AND low_mcc_entropy_x...,469,114,0.243070,0.025471,0.217599,9.542863,89,21,0.235955,0.0252,0.210755,9.363296,-0.179567,0.981183,-0.007115
13,card_not_present_flag AND low_mcc_entropy_x_hi...,469,114,0.243070,0.025471,0.217599,9.542863,89,21,0.235955,0.0252,0.210755,9.363296,-0.179567,0.981183,-0.007115
14,low_mcc_entropy_x_high_max_amount_30d AND low_...,469,114,0.243070,0.025471,0.217599,9.542863,89,21,0.235955,0.0252,0.210755,9.363296,-0.179567,0.981183,-0.007115
15,low_mcc_entropy_flag AND high_max_amount_30d_f...,469,114,0.243070,0.025471,0.217599,9.542863,89,21,0.235955,0.0252,0.210755,9.363296,-0.179567,0.981183,-0.007115
16,low_mcc_entropy_flag AND high_max_amount_30d_f...,469,114,0.243070,0.025471,0.217599,9.542863,89,21,0.235955,0.0252,0.210755,9.363296,-0.179567,0.981183,-0.007115
17,low_mcc_entropy_flag AND card_not_present_flag...,469,114,0.243070,0.025471,0.217599,9.542863,89,21,0.235955,0.0252,0.210755,9.363296,-0.179567,0.981183,-0.007115
18,low_mcc_entropy_flag AND low_mcc_entropy_x_hig...,469,114,0.243070,0.025471,0.217599,9.542863,89,21,0.235955,0.0252,0.210755,9.363296,-0.179567,0.981183,-0.007115
19,high_max_amount_30d_flag AND card_not_present_...,469,114,0.243070,0.025471,0.217599,9.542863,89,21,0.235955,0.0252,0.210755,9.363296,-0.179567,0.981183,-0.007115
20,high_max_amount_30d_flag AND card_not_present_...,469,114,0.243070,0.025471,0.217599,9.542863,89,21,0.235955,0.0252,0.210755,9.363296,-0.179567,0.981183,-0.007115
21,high_max_amount_30d_flag AND low_mcc_entropy_x...,469,114,0.243070,0.025471,0.217599,9.542863,89,21,0.235955,0.0252,0.210755,9.363296,-0.179567,0.981183,-0.007115
22,card_not_present_flag AND low_mcc_entropy_x_hi...,469,114,0.243070,0.025471,0.217599,9.542863,89,21,0.235955,0.0252,0.210755,9.363296,-0.179567,0.981183,-0.007115
23,low_mcc_entropy_flag AND high_max_amount_30d_flag,713,162,0.227209,0.025471,0.201738,8.920150,150,34,0.226667,0.0252,0.201467,8.994709,0.074559,1.008358,-0.000542
24,low_mcc_entropy_flag AND low_mcc_entropy_x_hig...,713,162,0.227209,0.025471,0.201738,8.920150,150,34,0.226667,0.0252,0.201467,8.994709,0.074559,1.008358,-0.000542
25,high_max_amount_30d_flag AND low_mcc_entropy_x...,713,162,0.227209,0.025471,0.201738,8.920150,150,34,0.226667,0.0252,0.201467,8.994709,0.074559,1.008358,-0.000542
26,low_mcc_entropy_flag AND high_max_amount_30d_f...,713,162,0.227209,0.025471,0.201738,8.920150,150,34,0.226667,0.0252,0.201467,8.994709,0.074559,1.008358,-0.000542
27,low_mcc_entropy_flag AND low_night_ratio_flag,696,181,0.260057,0.025471,0.234586,10.209772,159,36,0.226415,0.0252,0.201215,8.984726,-1.225046,0.880012,-0.033642
28,low_mcc_entropy_flag AND low_mcc_entropy_x_low...,696,181,0.260057,0.025471,0.234586,10.209772,159,36,0.226415,0.0252,0.201215,8.984726,-1.225046,0.880012,-0.033642
29,low_night_ratio_flag AND low_mcc_entropy_x_low...,696,181,0.260057,0.025471,0.234586,10.209772,159,36,0.226415,0.0252,0.201215,8.984726,-1.225046,0.880012,-0.033642

====================================================================================================
stable_categorical_pair_interactions.csv

,feature_a,value_a,feature_b,value_b,support_train,fraud_count_train,fraud_rate_train,global_fraud_rate_train,fraud_rate_diff_train,lift_train,support_valid,fraud_count_valid,fraud_rate_valid,global_fraud_rate_valid,fraud_rate_diff_valid,lift_valid,lift_diff_valid_train,lift_ratio_valid_train,fraud_rate_diff_valid_train
0,payment_channel,API_SERVER,merchant_country,VN,509,19,0.037328,0.025471,0.011857,1.465489,109,5,0.045872,0.0252,0.020672,1.820300,0.354811,1.242111,0.008543
1,time_period,late_evening,payment_channel,SMART_WATCH,887,35,0.039459,0.025471,0.013987,1.549142,161,7,0.043478,0.0252,0.018278,1.725328,0.176186,1.113731,0.004019
2,payment_channel,POS_TERMINAL,term_location,BRANCH_COUNTER,1418,48,0.033850,0.025471,0.008379,1.328959,295,12,0.040678,0.0252,0.015478,1.614205,0.285246,1.214638,0.006827
3,payment_channel,IVR_PHONE,merchant_country,ZA,524,18,0.034351,0.025471,0.008880,1.348615,104,4,0.038462,0.0252,0.013262,1.526252,0.177637,1.131718,0.004110
4,payment_channel,ATM,merchant_country,DE,452,15,0.033186,0.025471,0.007714,1.302865,107,4,0.037383,0.0252,0.012183,1.483459,0.180594,1.138613,0.004197
5,day_name,Saturday,payment_channel,MOBILE_APP,1469,54,0.036760,0.025471,0.011288,1.443174,324,12,0.037037,0.0252,0.011837,1.469724,0.026550,1.018397,0.000277
6,payment_channel,SMART_WATCH,merchant_country,ZA,471,24,0.050955,0.025471,0.025484,2.000493,121,4,0.033058,0.0252,0.007858,1.311819,-0.688673,0.655748,-0.017898
7,payment_channel,SMART_WATCH,merchant_country,HK,496,18,0.036290,0.025471,0.010819,1.424746,91,3,0.032967,0.0252,0.007767,1.308216,-0.116531,0.918210,-0.003323
8,payment_channel,IVR_PHONE,merchant_country,CN,499,19,0.038076,0.025471,0.012605,1.494857,123,4,0.032520,0.0252,0.007320,1.290489,-0.204368,0.863286,-0.005556
9,payment_channel,SMART_WATCH,merchant_country,MY,512,18,0.035156,0.025471,0.009685,1.380223,96,3,0.031250,0.0252,0.006050,1.240079,-0.140144,0.898463,-0.003906
10,payment_channel,IVR_PHONE,term_location,BRANCH_COUNTER,1383,46,0.033261,0.025471,0.007790,1.305817,328,10,0.030488,0.0252,0.005288,1.209834,-0.095984,0.926495,-0.002773

====================================================================================================
stable_categorical_patterns.csv

,feature,value,count_train,fraud_count_train,fraud_rate_train,global_fraud_rate_train,fraud_rate_diff_train,lift_train,count_valid,fraud_count_valid,fraud_rate_valid,global_fraud_rate_valid,fraud_rate_diff_valid,lift_valid,lift_diff_valid_train,lift_ratio_valid_train,fraud_rate_diff_valid_train
0,low_mcc_entropy_x_high_max_amount_30d,1,713,162,0.227209,0.025471,0.201738,8.920150,150,34,0.226667,0.0252,0.201467,8.994709,0.074559,1.008358,-0.000542
1,low_mcc_entropy_x_low_night_ratio,1,696,181,0.260057,0.025471,0.234586,10.209772,159,36,0.226415,0.0252,0.201215,8.984726,-1.225046,0.880012,-0.033642
2,low_night_ratio_x_high_max_amount_30d,1,728,124,0.170330,0.025471,0.144858,6.687087,157,32,0.203822,0.0252,0.178622,8.088161,1.401074,1.209519,0.033492
3,low_mcc_entropy_x_low_spending_trend,1,733,175,0.238745,0.025471,0.213273,9.373046,130,26,0.200000,0.0252,0.174800,7.936508,-1.436539,0.846737,-0.038745
4,night_unusual_group,very_high,2339,167,0.071398,0.025471,0.045927,2.803064,496,41,0.082661,0.0252,0.057461,3.280210,0.477146,1.170223,0.011263
5,low_mcc_entropy_x_card_not_present,1,4570,419,0.091685,0.025471,0.066213,3.599519,969,70,0.072239,0.0252,0.047039,2.866644,-0.732876,0.796396,-0.019445
6,night_ratio_group,very_low,6924,503,0.072646,0.025471,0.047174,2.852053,1503,108,0.071856,0.0252,0.046656,2.851440,-0.000613,0.999785,-0.000790
7,cross_border_x_low_country_diversity,1,1692,86,0.050827,0.025471,0.025356,1.995468,400,26,0.065000,0.0252,0.039800,2.579365,0.583897,1.292612,0.014173
8,night_ratio_group,low,14006,622,0.044410,0.025471,0.018938,1.743504,3085,133,0.043112,0.0252,0.017912,1.710787,-0.032717,0.981235,-0.001298
9,credit_util_risk_group,low,10611,381,0.035906,0.025471,0.010435,1.409663,2284,97,0.042469,0.0252,0.017269,1.685292,0.275629,1.195528,0.006563
10,night_unusual_group,high,7144,294,0.041153,0.025471,0.015682,1.615670,1406,58,0.041252,0.0252,0.016052,1.636975,0.021306,1.013187,0.000098
11,amount_to_max_group,below_half_max,21845,777,0.035569,0.025471,0.010097,1.396419,4602,174,0.037810,0.0252,0.012610,1.500383,0.103964,1.074451,0.002241
12,decline_rate_risk_group,low,16873,630,0.037338,0.025471,0.011866,1.465868,3634,136,0.037424,0.0252,0.012224,1.485092,0.019224,1.013114,0.000087
13,amount_to_max_group,near_max,19962,693,0.034716,0.025471,0.009245,1.362937,4312,136,0.031540,0.0252,0.006340,1.251583,-0.111354,0.918298,-0.003176

====================================================================================================
stable_numeric_patterns.csv

,feature,bin,count_train,fraud_count_train,fraud_rate_train,global_fraud_rate_train,fraud_rate_diff_train,lift_train,count_valid,fraud_count_valid,fraud_rate_valid,global_fraud_rate_valid,fraud_rate_diff_valid,lift_valid,lift_diff_valid_train,lift_ratio_valid_train,fraud_rate_diff_valid_train
0,max_amount_30d,"(225176.777, inf]",7000,439,0.062714,0.025471,0.037243,2.462142,1444,115,0.079640,0.0252,0.054440,3.160313,0.698171,1.283562,0.016926
1,mcc_entropy_30d,"(-inf, 0.393]",7009,625,0.089171,0.025471,0.063700,3.500827,1525,112,0.073443,0.0252,0.048243,2.914390,-0.586437,0.832486,-0.015728
2,night_ratio_30d,"(-inf, 0.101]",7038,511,0.072606,0.025471,0.047134,2.850482,1531,111,0.072502,0.0252,0.047302,2.877049,0.026567,1.009320,-0.000104
3,spending_trend,"(-inf, 0.584]",7002,463,0.066124,0.025471,0.040653,2.596005,1400,89,0.063571,0.0252,0.038371,2.522676,-0.073330,0.971753,-0.002553
4,distinct_countries_30d,"(-inf, 3.0]",8464,525,0.062027,0.025471,0.036556,2.435176,1842,114,0.061889,0.0252,0.036689,2.455923,0.020747,1.008520,-0.000138
5,mcc_entropy_30d,"(0.393, 0.788]",6992,413,0.059068,0.025471,0.033596,2.318971,1405,85,0.060498,0.0252,0.035298,2.400723,0.081752,1.035254,0.001431
6,night_unusual_score,"(0.705, inf]",6991,381,0.054499,0.025471,0.029027,2.139599,1410,84,0.059574,0.0252,0.034374,2.364066,0.224467,1.104911,0.005076
7,spending_trend,"(0.584, 1.073]",7008,331,0.047232,0.025471,0.021760,1.854303,1522,81,0.053219,0.0252,0.028019,2.111883,0.257580,1.138910,0.005988
8,std_amount_30d,"(1.12, 1.25]",6710,292,0.043517,0.025471,0.018046,1.708469,1392,73,0.052443,0.0252,0.027243,2.081053,0.372584,1.218081,0.008925
9,std_amount_30d,"(-inf, 1.12]",7397,389,0.052589,0.025471,0.027117,2.064623,1560,80,0.051282,0.0252,0.026082,2.035002,-0.029621,0.985653,-0.001307
10,night_ratio_30d,"(0.101, 0.201]",6999,362,0.051722,0.025471,0.026250,2.030576,1502,71,0.047270,0.0252,0.022070,1.875806,-0.154770,0.923780,-0.004451
11,distinct_countries_30d,"(3.0, 6.0]",8280,363,0.043841,0.025471,0.018369,1.721167,1860,87,0.046774,0.0252,0.021574,1.856119,0.134952,1.078407,0.002934
12,decline_rate_30d,"(-inf, 0.067]",7161,309,0.043150,0.025471,0.017679,1.694071,1614,65,0.040273,0.0252,0.015073,1.598120,-0.095951,0.943361,-0.002878
13,max_amount_30d,"(200126.978, 225176.777]",7000,370,0.052857,0.025471,0.027386,2.075154,1517,54,0.035597,0.0252,0.010397,1.412562,-0.662592,0.680702,-0.017261

====================================================================================================
stable_priority_interactions.csv

,rule,support_train,fraud_count_train,fraud_rate_train,global_fraud_rate_train,fraud_rate_diff_train,lift_train,support_valid,fraud_count_valid,fraud_rate_valid,global_fraud_rate_valid,fraud_rate_diff_valid,lift_valid,lift_diff_valid_train,lift_ratio_valid_train,fraud_rate_diff_valid_train
0,low_mcc_entropy AND low_night_ratio AND card_n...,479,128,0.267223,0.025471,0.241752,10.491103,94,25,0.265957,0.0252,0.240757,10.553867,0.062764,1.005983,-0.001266
1,low_mcc_entropy AND high_max_amount_30d,713,162,0.227209,0.025471,0.201738,8.920150,150,34,0.226667,0.0252,0.201467,8.994709,0.074559,1.008358,-0.000542
2,low_mcc_entropy AND low_night_ratio,696,181,0.260057,0.025471,0.234586,10.209772,159,36,0.226415,0.0252,0.201215,8.984726,-1.225046,0.880012,-0.033642
3,low_night_ratio AND high_max_amount_30d,728,124,0.170330,0.025471,0.144858,6.687087,157,32,0.203822,0.0252,0.178622,8.088161,1.401074,1.209519,0.033492
4,low_mcc_entropy AND low_spending_trend,733,175,0.238745,0.025471,0.213273,9.373046,130,26,0.200000,0.0252,0.174800,7.936508,-1.436539,0.846737,-0.038745
5,low_night_ratio AND night_transaction,2401,171,0.071220,0.025471,0.045749,2.796087,509,41,0.080550,0.0252,0.055350,3.196432,0.400346,1.143181,0.009330
6,low_mcc_entropy AND card_not_present,4570,419,0.091685,0.025471,0.066213,3.599519,969,70,0.072239,0.0252,0.047039,2.866644,-0.732876,0.796396,-0.019445
7,cross_border AND low_country_diversity,1692,86,0.050827,0.025471,0.025356,1.995468,400,26,0.065000,0.0252,0.039800,2.579365,0.583897,1.292612,0.014173

====================================================================================================
stable_segments.csv

,segment_name,support_train,fraud_count_train,fraud_rate_train,global_fraud_rate_train,fraud_rate_diff_train,lift_train,support_valid,fraud_count_valid,fraud_rate_valid,global_fraud_rate_valid,fraud_rate_diff_valid,lift_valid,lift_diff_valid_train,lift_ratio_valid_train,fraud_rate_diff_valid_train
0,night_unusual,2401,171,0.071220,0.025471,0.045749,2.796087,496,41,0.082661,0.0252,0.057461,3.280210,0.484123,1.173143,0.011441
1,very_low_mcc_entropy,3510,339,0.096581,0.025471,0.071110,3.791746,750,61,0.081333,0.0252,0.056133,3.227513,-0.564233,0.851194,-0.015248
2,high_max_amount_30d,7000,439,0.062714,0.025471,0.037243,2.462142,1500,116,0.077333,0.0252,0.052133,3.068783,0.606641,1.246387,0.014619
3,low_night_ratio,7038,511,0.072606,0.025471,0.047134,2.850482,1500,110,0.073333,0.0252,0.048133,2.910053,0.059571,1.020898,0.000727
4,low_mcc_entropy,7009,625,0.089171,0.025471,0.063700,3.500827,1503,110,0.073187,0.0252,0.047987,2.904244,-0.596583,0.829588,-0.015984
5,low_country_diversity,8464,525,0.062027,0.025471,0.036556,2.435176,1842,114,0.061889,0.0252,0.036689,2.455923,0.020747,1.008520,-0.000138

====================================================================================================
strong_categorical_patterns_train.csv

                                  feature           value  count  fraud_count  fraud_rate  global_fraud_rate  fraud_rate_diff       lift
0       low_mcc_entropy_x_low_night_ratio               1    696          181    0.260057           0.025471         0.234586  10.209772
1    low_mcc_entropy_x_low_spending_trend               1    733          175    0.238745           0.025471         0.213273   9.373046
2   low_mcc_entropy_x_high_max_amount_30d               1    713          162    0.227209           0.025471         0.201738   8.920150
3   low_night_ratio_x_high_max_amount_30d               1    728          124    0.170330           0.025471         0.144858   6.687087
4      low_mcc_entropy_x_card_not_present               1   4570          419    0.091685           0.025471         0.066213   3.599519
5                       night_ratio_group        very_low   6924          503    0.072646           0.025471         0.047174   2.852053
6                     night_unusual_group       very_high   2339          167    0.071398           0.025471         0.045927   2.803064
7    cross_border_x_low_country_diversity               1   1692           86    0.050827           0.025471         0.025356   1.995468
8                       night_ratio_group             low  14006          622    0.044410           0.025471         0.018938   1.743504
9                     night_unusual_group            high   7144          294    0.041153           0.025471         0.015682   1.615670
10                decline_rate_risk_group             low  16873          630    0.037338           0.025471         0.011866   1.465868
11                 credit_util_risk_group             low  10611          381    0.035906           0.025471         0.010435   1.409663
12                    amount_to_max_group  below_half_max  21845          777    0.035569           0.025471         0.010097   1.396419
13                    amount_to_max_group        near_max  19962          693    0.034716           0.025471         0.009245   1.362937

====================================================================================================
strong_numeric_patterns_train.csv

                   feature                       bin  count  fraud_count  fraud_rate  global_fraud_rate  fraud_rate_diff      lift   min_value   max_value     mean_value
0          mcc_entropy_30d             (-inf, 0.393]   7009          625    0.089171           0.025471         0.063700  3.500827       0.000       0.393       0.197092
1          night_ratio_30d             (-inf, 0.101]   7038          511    0.072606           0.025471         0.047134  2.850482       0.000       0.101       0.050896
2           spending_trend             (-inf, 0.584]   7002          463    0.066124           0.025471         0.040653  2.596005       0.100       0.584       0.341220
3           max_amount_30d         (225176.777, inf]   7000          439    0.062714           0.025471         0.037243  2.462142  225178.460  249999.110  237616.020059
4   distinct_countries_30d               (-inf, 3.0]   8464          525    0.062027           0.025471         0.036556  2.435176       1.000       3.000       1.995156
5          mcc_entropy_30d            (0.393, 0.788]   6992          413    0.059068           0.025471         0.033596  2.318971       0.394       0.788       0.590709
6      night_unusual_score              (0.705, inf]   6991          381    0.054499           0.025471         0.029027  2.139599       0.706       1.000       0.851811
7           max_amount_30d  (200126.978, 225176.777]   7000          370    0.052857           0.025471         0.027386  2.075154  200127.690  225176.590  212685.577433
8           std_amount_30d              (-inf, 1.12]   7397          389    0.052589           0.025471         0.027117  2.064623       1.000       1.120       1.061372
9          night_ratio_30d            (0.101, 0.201]   6999          362    0.051722           0.025471         0.026250  2.030576       0.102       0.201       0.151508
10          spending_trend            (0.584, 1.073]   7008          331    0.047232           0.025471         0.021760  1.854303       0.585       1.073       0.828886
11  distinct_countries_30d                (3.0, 6.0]   8280          363    0.043841           0.025471         0.018369  1.721167       4.000       6.000       5.005556
12          std_amount_30d              (1.12, 1.25]   6710          292    0.043517           0.025471         0.018046  1.708469       1.130       1.250       1.188274
13        decline_rate_30d             (-inf, 0.067]   7161          309    0.043150           0.025471         0.017679  1.694071       0.002       0.067       0.047687

====================================================================================================
train_behavior_thresholds.csv

   low_mcc_entropy_q10  low_night_ratio_q10  high_max_amount_q90  low_spending_trend_q10  low_country_diversity_q10  high_device_diversity_q90  high_decline_rate_q90  high_ip_score_q90
0                0.393                0.101           225176.777                   0.584                        3.0                       36.0                  0.283             0.5123

====================================================================================================
train_features_preview.csv

,amount,currency,local_timestamp,payment_channel,merchant_country,mcc,card_present,ip_risk,device_id,card_entry_mode,auth_result,merchant_id,pin_verif_method,tokenised,recurring_flag,cross_border,card_activation_age,auth_characteristics,message_type,mean_amount_30d,std_amount_30d,max_amount_30d,txn_counts,distinct_merchants_7d,distinct_countries_30d,online_share_7d,night_ratio_30d,days_since_last_txn,decline_rate_30d,chargebacks_365d,device_diversity_30d,mcc_entropy_30d,credit_util_today,spending_trend,term_location,fraud,ip_address,ip_score,txn_count_7d,txn_count_30d,txn_count_ratio_7d_30d,ip_is_private,ip_score_bin,transaction_datetime,hour,day_of_week,day_name,is_weekend,is_night_txn,month,day,year,time_period,night_unusual_score,is_night_unusual,amount_invalid_flag,std_amount_30d_zero_flag,mean_amount_30d_zero_flag,duplicate_row_flag,ip_score_risk_group,decline_rate_risk_group,credit_util_risk_group,txn_count_7d_group,txn_velocity_group,night_ratio_group,amount_to_mean_30d,amount_to_mean_group,amount_to_max_30d,amount_to_max_group,low_mcc_entropy_flag,low_night_ratio_flag,high_max_amount_30d_flag,low_spending_trend_flag,low_country_diversity_flag,high_device_diversity_flag,high_decline_rate_flag,high_ip_score_flag,night_transaction_flag,card_not_present_flag,cross_border_flag,tokenised_flag,night_unusual_group,high_ip_high_amount_flag,high_decline_high_amount_flag,private_ip_high_score_flag,high_velocity_high_amount_flag,low_mcc_entropy_x_low_night_ratio,low_mcc_entropy_x_high_max_amount_30d,low_mcc_entropy_x_low_spending_trend,low_mcc_entropy_x_card_not_present,low_night_ratio_x_high_max_amount_30d,cross_border_x_low_country_diversity,high_ip_score_x_card_not_present
0,71385.62,GBP,2025-03-07 07:19:19,MOBILE_APP,PH,7765,False,"{'ip': '174.77.134.216', 'score': 0.3064}",DEV-5C528B7234584CFE,CONTACTLESS,CVV_PASS,MID-5BA3C327F75C,NONE,False,MOTO_MAIL,False,3986,CRYPTOGRAM_PRESENT,0200-FinReq,6.75,1.40,212755.87,"(48, 69)",21,10,0.220,0.760,65,0.282,0,32,2.124,1.452,4.548,CALL_CENTER,0,174.77.134.216,0.3064,48.0,69.0,0.685714,0,medium,2025-03-07 07:19:19,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,medium,medium,very_high,gt_20,medium,high,9211.047742,extreme,0.335527,below_half_max,0,0,0,0,0,0,0,0,0,1,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
1,41958.74,EUR,2025-03-07 07:19:30,API_SERVER,IN,7995,True,"{'ip': '231.148.136.200', 'score': 0.4186}",DEV-F5CB0AA260AF42F8,TOKEN_IN_APP,3DS_PASS,MID-36FC92EFCEE0,SIGNATURE,True,MOTO_PHONE,True,3804,CRYPTOGRAM_PRESENT,0200-FinReq,12.94,1.97,230333.61,"(11, 13)",120,20,0.135,0.236,30,0.095,0,24,1.742,0.328,4.655,ONLINE_PORTAL,0,231.148.136.200,0.4186,11.0,13.0,0.785714,0,medium,2025-03-07 07:19:30,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,medium,low,medium,11_20,medium,low,3009.952654,extreme,0.182164,below_half_max,0,0,1,0,0,0,0,0,0,0,1,1,not_night,0,0,0,0,0,0,0,0,0,0,0
2,153871.73,USD,2025-03-07 07:21:59,WEB_BROWSER,ZA,3038,False,"{'ip': '77.110.52.227', 'score': 0.171}",DEV-176EDAC722944DBA,CONTACTLESS,3DS_FAIL,MID-06909B008FFA,ONLINE_PIN,False,RECURRING_SUBSCRIPTION,False,2234,CRYPTOGRAM_PRESENT,0400-Reversal,5.31,1.18,141022.77,"(72, 156)",1,5,0.083,0.099,89,0.101,0,3,2.480,1.486,3.255,WEARABLE_PAY,0,77.110.52.227,0.1710,72.0,156.0,0.458599,0,low,2025-03-07 07:21:59,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,low,medium,very_high,gt_20,low,very_low,24385.377179,extreme,1.091105,above_max,0,1,0,0,0,0,0,0,0,1,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
3,12640.64,EUR,2025-03-07 07:22:41,WEB_BROWSER,PH,4561,False,"{'ip': '29.204.33.254', 'score': 0.4649}",DEV-43083AB6E205477A,CHIP,3DS_FAIL,MID-0470B187B553,ONLINE_PIN,False,RECURRING_SUBSCRIPTION,True,554,CARD_PRESENT,0500-Advice,7.09,2.62,162129.41,"(97, 373)",64,3,0.635,0.301,29,0.312,0,12,0.811,1.370,3.559,MOBILE_APP,0,29.204.33.254,0.4649,97.0,373.0,0.259358,0,medium,2025-03-07 07:22:41,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,medium,high,very_high,gt_20,low,medium,1562.501854,extreme,0.077966,below_half_max,0,0,0,0,1,0,1,0,0,1,1,0,not_night,0,0,0,0,0,0,0,0,0,1,0
4,149437.12,IDR,2025-03-07 07:22:58,IVR_PHONE,ZA,7032,True,"{'ip': '207.35.255.86', 'score': 0.2651}",DEV-26C462E4AE6047DC,CONTACTLESS,3DS_FAIL,MID-6A15337D76BB,OFFLINE_PIN,True,INSTALLMENT_PLAN,False,1713,CARD_PRESENT,0510-AdviceRsp,5.38,2.42,226321.03,"(15, 155)",101,2,0.252,0.858,134,0.041,0,7,0.840,0.396,4.716,KIOSK,0,207.35.255.86,0.2651,15.0,155.0,0.096154,0,medium,2025-03-07 07:22:58,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,medium,low,medium,11_20,very_low,high,23422.746082,extreme,0.660285,near_max,0,0,1,0,1,0,0,0,0,0,0,1,not_night,0,0,0,0,0,0,0,0,0,0,0
5,163092.59,CNY,2025-03-07 07:23:50,WEB_BROWSER,FR,3199,False,"{'ip': '27.40.94.227', 'score': 0.2395}",DEV-DCD6F147979F4BF4,QR_CODE,CVV_FAIL,MID-B8B4AB0E5975,ONLINE_PIN,False,MOTO_MAIL,True,2024,CARD_PRESENT,0200-FinReq,5.47,1.38,97796.12,"(39, 159)",75,22,0.269,0.775,88,0.115,0,31,0.560,0.921,3.316,POS_TERMINAL,0,27.40.94.227,0.2395,39.0,159.0,0.243750,0,medium,2025-03-07 07:23:50,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,medium,medium,very_high,gt_20,low,high,25207.510046,extreme,1.667663,above_max,0,0,0,0,0,0,0,0,0,1,1,0,not_night,0,0,0,0,0,0,0,0,0,0,0
6,122032.61,USD,2025-03-07 07:23:55,WEB_BROWSER,VN,5064,True,"{'ip': '115.174.211.223', 'score': 0.2604}",DEV-9FEC8718F2EC417F,MANUAL_KEYED,CVV_PASS,MID-74ACD0B988B5,ONLINE_PIN,True,INSTALLMENT_PLAN,True,2758,FORCE_POST,0510-AdviceRsp,12.11,1.56,48539.81,"(52, 499)",72,11,0.336,0.498,104,0.361,0,9,1.817,1.576,3.075,KIOSK,0,115.174.211.223,0.2604,52.0,499.0,0.104000,0,medium,2025-03-07 07:23:55,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,medium,high,very_high,gt_20,very_low,medium,9308.360793,extreme,2.514021,much_above_max,0,0,0,0,0,0,1,0,0,0,1,1,not_night,0,0,0,0,0,0,0,0,0,0,0
7,59565.53,USD,2025-03-07 07:24:13,IVR_PHONE,JP,7702,False,"{'ip': '45.176.31.253', 'score': 0.0829}",DEV-7FDB800C209E4336,TOKEN_IN_APP,AVS_FAIL,MID-8827BA5BCEBD,OFFLINE_PIN,False,RECURRING_SUBSCRIPTION,True,725,CRYPTOGRAM_PRESENT,0110-AuthRsp,6.78,1.95,50464.27,"(76, 225)",23,21,0.017,0.766,139,0.146,0,36,3.705,1.402,2.244,ONLINE_PORTAL,0,45.176.31.253,0.0829,76.0,225.0,0.336283,0,low,2025-03-07 07:24:13,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,low,medium,very_high,gt_20,low,high,7656.237789,extreme,1.180327,above_max,0,0,0,0,0,1,0,0,0,1,1,0,not_night,0,0,0,0,0,0,0,0,0,0,0
8,114575.30,USD,2025-03-07 07:25:08,ATM,GB,4515,False,"{'ip': '132.21.130.190', 'score': 0.4568}",DEV-70087AA76E7B4EC1,QR_CODE,BIOMETRIC_FAIL,MID-D762B1587991,SIGNATURE,True,SINGLE_PURCHASE,False,1561,FALLBACK_MAG,0500-Advice,6.42,1.77,181952.57,"(35, 463)",69,13,0.994,0.682,55,0.268,0,31,2.345,0.451,3.942,CALL_CENTER,0,132.21.130.190,0.4568,35.0,463.0,0.075431,0,medium,2025-03-07 07:25:08,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,medium,medium,medium,gt_20,very_low,high,15441.415094,extreme,0.629695,near_max,0,0,0,0,0,0,0,0,0,1,0,1,not_night,0,0,0,0,0,0,0,0,0,0,0
9,41689.59,EUR,2025-03-07 07:26:20,IVR_PHONE,HK,3257,False,"{'ip': '80.206.229.5', 'score': 0.1576}",DEV-6C1B29951D084E00,TOKEN_IN_APP,BIOMETRIC_PASS,MID-C85B9D1C10C6,ONLINE_PIN,False,INSTALLMENT_PLAN,False,2176,MOBILE_TOKEN,0110-AuthRsp,7.18,2.54,109039.92,"(28, 234)",63,2,0.636,0.304,19,0.191,0,20,1.412,1.863,1.241,WEARABLE_PAY,0,80.206.229.5,0.1576,28.0,234.0,0.119149,0,low,2025-03-07 07:26:20,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,low,medium,very_high,gt_20,very_low,medium,5096.526895,extreme,0.382330,below_half_max,0,0,0,0,1,0,0,0,0,1,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
10,71186.37,KRW,2025-03-07 07:27:27,IVR_PHONE,AE,3126,True,"{'ip': '120.192.146.107', 'score': 0.0881}",DEV-DC2C27D6AC8247E6,CONTACTLESS,BIOMETRIC_PASS,MID-81F814D1428A,ONLINE_PIN,True,MOTO_PHONE,True,2318,CRYPTOGRAM_PRESENT,0110-AuthRsp,10.13,1.44,167692.12,"(39, 423)",89,22,0.910,0.670,35,0.090,0,37,1.423,0.942,0.484,POS_TERMINAL,0,120.192.146.107,0.0881,39.0,423.0,0.091981,0,low,2025-03-07 07:27:27,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,low,low,very_high,gt_20,very_low,high,6395.900270,extreme,0.424504,below_half_max,0,0,0,1,0,1,0,0,0,0,1,1,not_night,0,0,0,0,0,0,0,0,0,0,0
11,36855.02,USD,2025-03-07 07:27:37,SMART_WATCH,GB,4480,False,"{'ip': '36.148.101.28', 'score': 0.1993}",DEV-C34538B888A0477E,CHIP,AVS_FAIL,MID-D300D4659C52,ONLINE_PIN,False,MOTO_PHONE,False,3890,FORCE_POST,0100-AuthReq,12.18,4.05,222441.42,"(21, 490)",52,24,0.834,0.628,135,0.084,0,29,0.384,1.166,0.909,MOBILE_APP,0,36.148.101.28,0.1993,21.0,490.0,0.042770,0,low,2025-03-07 07:27:37,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,low,low,very_high,gt_20,very_low,high,2796.283763,extreme,0.165683,below_half_max,1,0,0,0,0,0,0,0,0,1,0,0,not_night,0,0,0,0,0,0,0,1,0,0,0
12,13175.28,USD,2025-03-07 07:30:18,WEB_BROWSER,IN,7667,False,"{'ip': '82.152.167.193', 'score': 0.4542}",DEV-A52423F1DF924C42,CONTACTLESS,3DS_FAIL,MID-81CEA3976DDD,ONLINE_PIN,False,RECURRING_SUBSCRIPTION,False,1857,FALLBACK_MAG,0110-AuthRsp,8.55,2.46,18963.19,"(47, 152)",112,7,0.528,0.300,68,0.146,0,15,2.474,1.508,1.251,MOBILE_APP,0,82.152.167.193,0.4542,47.0,152.0,0.307190,0,medium,2025-03-07 07:30:18,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,medium,medium,very_high,gt_20,low,low,1379.610471,extreme,0.694745,near_max,0,0,0,0,0,0,0,0,0,1,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
13,104648.79,USD,2025-03-07 07:32:52,WEB_BROWSER,MY,4356,False,"{'ip': '26.21.122.116', 'score': 0.2897}",DEV-030EBF59B13F44F6,CHIP,AVS_PASS,MID-57F54D166724,SIGNATURE,False,RECURRING_SUBSCRIPTION,False,2692,MOBILE_TOKEN,0510-AdviceRsp,5.56,1.86,70907.14,"(89, 228)",60,15,0.007,0.034,158,0.282,0,36,3.116,0.947,3.151,MOBILE_APP,0,26.21.122.116,0.2897,89.0,228.0,0.388646,0,medium,2025-03-07 07:32:52,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,medium,medium,very_high,gt_20,low,very_low,15952.559451,extreme,1.475836,above_max,0,1,0,0,0,1,0,0,0,1,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
14,180837.71,VND,2025-03-07 07:34:30,WEB_BROWSER,BR,5779,True,"{'ip': '30.64.165.138', 'score': 0.3918}",DEV-F5FC83B7EA104023,QR_CODE,AVS_FAIL,MID-0C8934C70B2F,NONE,True,MOTO_MAIL,False,1320,CRYPTOGRAM_PRESENT,0510-AdviceRsp,6.37,3.07,44652.78,"(6, 477)",84,25,0.027,0.532,103,0.095,0,1,1.105,1.252,4.535,CALL_CENTER,0,30.64.165.138,0.3918,6.0,477.0,0.012552,0,medium,2025-03-07 07:34:30,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,medium,low,very_high,6_10,very_low,medium,24537.002714,extreme,4.049774,much_above_max,0,0,0,0,0,0,0,0,0,0,0,1,not_night,0,0,0,0,0,0,0,0,0,0,0
15,59867.93,CAD,2025-03-07 07:36:01,IVR_PHONE,VN,4325,True,"{'ip': '251.229.132.228', 'score': 0.6292}",DEV-FA61EEB3D72B4316,QR_CODE,BIOMETRIC_FAIL,MID-6FD3DCCBBE54,SIGNATURE,True,INSTALLMENT_PLAN,False,2432,FORCE_POST,0510-AdviceRsp,5.41,1.50,72365.52,"(18, 37)",19,10,0.849,0.925,147,0.188,0,34,3.365,1.626,4.105,KIOSK,0,251.229.132.228,0.6292,18.0,37.0,0.473684,0,high,2025-03-07 07:36:01,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,high,medium,very_high,11_20,low,high,9339.770671,extreme,0.827288,near_max,0,0,0,0,0,0,0,1,0,0,0,1,not_night,0,0,0,0,0,0,0,0,0,0,0
16,87839.12,VND,2025-03-07 07:36:25,POS_TERMINAL,SG,7827,False,"{'ip': '58.197.158.217', 'score': 0.3199}",DEV-A04AC4F6499147D2,CHIP,AVS_FAIL,MID-A769608BFC73,NONE,False,MOTO_PHONE,False,776,CRYPTOGRAM_PRESENT,0210-FinRsp,6.48,2.62,139804.23,"(39, 45)",3,25,0.737,0.868,1,0.271,0,25,3.587,1.819,1.159,ONLINE_PORTAL,0,58.197.158.217,0.3199,39.0,45.0,0.847826,0,medium,2025-03-07 07:36:25,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,medium,medium,very_high,gt_20,high,high,11743.197861,extreme,0.628296,near_max,0,0,0,0,0,0,0,0,0,1,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
17,46220.51,EUR,2025-03-07 07:37:12,MOBILE_APP,KR,3107,True,"{'ip': '50.202.5.47', 'score': 0.0947}",DEV-A1134CBAB726437A,CHIP,AVS_FAIL,MID-46C9243CC96D,ONLINE_PIN,False,SINGLE_PURCHASE,False,2803,MOBILE_TOKEN,0110-AuthRsp,7.31,1.25,51450.88,"(95, 190)",68,16,0.630,0.148,1,0.325,0,20,3.997,0.140,3.010,BRANCH_COUNTER,0,50.202.5.47,0.0947,95.0,190.0,0.497382,0,low,2025-03-07 07:37:12,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,low,high,low,gt_20,low,low,5562.034898,extreme,0.898325,near_max,0,0,0,0,0,0,1,0,0,0,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
18,50111.02,USD,2025-03-07 07:38:11,SMART_WATCH,AE,4732,False,"{'ip': '227.86.201.12', 'score': 0.3357}",DEV-DC36F0A6E5204009,QR_CODE,CVV_FAIL,MID-B2952BC12A25,SIGNATURE,False,SINGLE_PURCHASE,False,990,FALLBACK_MAG,0210-FinRsp,5.83,1.21,62576.19,"(25, 335)",109,21,0.191,0.773,150,0.093,0,40,1.805,1.100,4.922,ONLINE_PORTAL,0,227.86.201.12,0.3357,25.0,335.0,0.074405,0,medium,2025-03-07 07:38:11,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,medium,low,very_high,gt_20,very_low,high,7336.898975,extreme,0.800787,near_max,0,0,0,0,0,1,0,0,0,1,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
19,118767.61,USD,2025-03-07 07:38:34,WEB_BROWSER,SG,4144,False,"{'ip': '121.189.87.160', 'score': 0.1792}",DEV-960193313E69471F,TOKEN_IN_APP,3DS_PASS,MID-6E7B13820CE7,OFFLINE_PIN,True,MOTO_MAIL,True,1748,MOBILE_TOKEN,0510-AdviceRsp,10.18,2.01,217301.95,"(20, 290)",18,11,0.115,0.451,23,0.090,0,1,3.658,1.111,2.244,BRANCH_COUNTER,0,121.189.87.160,0.1792,20.0,290.0,0.068729,0,low,2025-03-07 07:38:34,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,low,low,very_high,11_20,very_low,medium,10623.220930,extreme,0.546553,near_max,0,0,0,0,0,0,0,0,0,1,1,1,not_night,0,0,0,0,0,0,0,0,0,0,0
20,166669.51,USD,2025-03-07 07:39:33,POS_TERMINAL,KR,3006,False,"{'ip': '142.226.79.102', 'score': 0.5467}",DEV-B42D25CF141947D9,QR_CODE,3DS_FAIL,MID-728C1DDDBB87,OFFLINE_PIN,True,MOTO_PHONE,True,1332,CARD_PRESENT,0200-FinReq,5.47,1.97,34956.72,"(6, 330)",108,1,0.317,0.315,158,0.130,0,2,0.965,1.830,3.720,POS_TERMINAL,0,142.226.79.102,0.5467,6.0,330.0,0.018127,0,high,2025-03-07 07:39:33,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,high,medium,very_high,6_10,very_low,medium,25760.357032,extreme,4.767745,much_above_max,0,0,0,0,1,0,0,1,0,1,1,1,not_night,0,0,0,0,0,0,0,0,0,1,1
21,35014.00,GBP,2025-03-07 07:40:29,POS_TERMINAL,CN,3150,False,"{'ip': '35.121.84.143', 'score': 0.0271}",DEV-DD32417A1EAD4FC0,QR_CODE,CVV_PASS,MID-74F1AAF6900F,ONLINE_PIN,True,SINGLE_PURCHASE,False,1632,E_COMMERCE,0420-RepeatRev,7.05,1.06,205443.97,"(6, 80)",39,19,0.732,0.306,180,0.251,0,4,0.008,0.138,0.398,KIOSK,1,35.121.84.143,0.0271,6.0,80.0,0.074074,0,low,2025-03-07 07:40:29,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,low,medium,low,6_10,very_low,medium,4349.565217,extreme,0.170430,below_half_max,1,0,0,1,0,0,0,0,0,1,0,1,not_night,0,0,0,0,0,0,1,1,0,0,0
22,22630.77,SGD,2025-03-07 07:41:04,POS_TERMINAL,PH,7964,True,"{'ip': '66.24.146.163', 'score': 0.1973}",DEV-E74734D6409D48EB,QR_CODE,3DS_PASS,MID-68CAE07FFC9A,OFFLINE_PIN,False,SINGLE_PURCHASE,False,2972,FALLBACK_MAG,0400-Reversal,6.92,3.48,9124.53,"(14, 413)",114,3,0.873,0.942,169,0.107,0,15,3.171,0.504,1.751,WEARABLE_PAY,0,66.24.146.163,0.1973,14.0,413.0,0.033816,0,low,2025-03-07 07:41:04,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,low,medium,medium,11_20,very_low,high,2857.420455,extreme,2.479940,much_above_max,0,0,0,0,1,0,0,0,0,0,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
23,144774.94,GBP,2025-03-07 07:41:51,WEB_BROWSER,ID,5447,False,"{'ip': '2.51.70.28', 'score': 0.0128}",DEV-E97AE53EC08E42C5,MANUAL_KEYED,3DS_PASS,MID-CEA4ADAC53EF,ONLINE_PIN,True,RECURRING_SUBSCRIPTION,False,1504,MOBILE_TOKEN,0110-AuthRsp,5.55,2.68,127411.23,"(10, 183)",97,20,0.878,0.221,17,0.121,0,16,0.456,1.957,2.787,MOBILE_APP,0,2.51.70.28,0.0128,10.0,183.0,0.054348,0,low,2025-03-07 07:41:51,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,low,medium,very_high,6_10,very_low,low,22103.044275,extreme,1.136272,above_max,0,0,0,0,0,0,0,0,0,1,0,1,not_night,0,0,0,0,0,0,0,0,0,0,0
24,82382.57,GBP,2025-03-07 07:43:21,ATM,TH,3204,True,"{'ip': '204.204.144.62', 'score': 0.312}",DEV-6AB837DC11924796,MAGSTRIPE,BIOMETRIC_PASS,MID-CFC5DCDD075C,ONLINE_PIN,False,INSTALLMENT_PLAN,False,1457,FORCE_POST,0110-AuthRsp,17.25,2.26,124771.06,"(61, 253)",26,12,0.723,0.362,60,0.089,0,38,1.470,0.440,3.818,KIOSK,0,204.204.144.62,0.3120,61.0,253.0,0.240157,0,medium,2025-03-07 07:43:21,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,medium,low,medium,gt_20,low,medium,4514.113425,extreme,0.660265,near_max,0,0,0,0,0,1,0,0,0,0,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
25,131261.39,KRW,2025-03-07 07:44:35,SMART_WATCH,JP,4523,False,"{'ip': '136.250.153.154', 'score': 0.2826}",DEV-A0412AD347204CA1,MANUAL_KEYED,BIOMETRIC_PASS,MID-F52513E2BA1A,OFFLINE_PIN,False,INSTALLMENT_PLAN,False,1128,CRYPTOGRAM_PRESENT,0200-FinReq,5.44,1.17,139794.23,"(18, 27)",3,9,0.126,0.474,37,0.091,0,29,2.204,0.317,4.826,ONLINE_PORTAL,0,136.250.153.154,0.2826,18.0,27.0,0.642857,0,medium,2025-03-07 07:44:35,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,medium,low,medium,11_20,medium,medium,20382.203416,extreme,0.938955,near_max,0,0,0,0,0,0,0,0,0,1,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
26,148388.04,USD,2025-03-07 07:44:43,IVR_PHONE,GB,4601,False,"{'ip': '222.155.45.67', 'score': 0.2687}",DEV-1FB51ED417894055,CONTACTLESS,CVV_PASS,MID-CDF2223A5974,ONLINE_PIN,False,MOTO_MAIL,False,3451,FALLBACK_MAG,0110-AuthRsp,61.45,2.80,217761.64,"(91, 96)",49,8,0.177,0.481,159,0.077,0,4,0.852,1.679,2.251,BRANCH_COUNTER,0,222.155.45.67,0.2687,91.0,96.0,0.938144,0,medium,2025-03-07 07:44:43,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,medium,low,very_high,gt_20,high,medium,2376.109528,extreme,0.681421,near_max,0,0,0,0,0,0,0,0,0,1,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
27,100793.68,USD,2025-03-07 07:45:28,MOBILE_APP,JP,5632,False,"{'ip': '89.91.97.97', 'score': 0.5043}",DEV-7CA302EFA24840E9,TOKEN_IN_APP,AVS_FAIL,MID-FA713FEDE017,ONLINE_PIN,True,MOTO_MAIL,False,2023,FALLBACK_MAG,0210-FinRsp,5.98,3.28,171983.62,"(81, 484)",93,7,0.733,0.304,44,0.058,0,34,3.468,1.548,2.627,MOBILE_APP,0,89.91.97.97,0.5043,81.0,484.0,0.167010,0,high,2025-03-07 07:45:28,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,high,low,very_high,gt_20,very_low,medium,14440.355301,extreme,0.586062,near_max,0,0,0,0,0,0,0,0,0,1,0,1,not_night,0,0,0,0,0,0,0,0,0,0,0
28,18157.48,EUR,2025-03-07 07:45:31,IVR_PHONE,US,4598,False,"{'ip': '104.110.93.66', 'score': 0.1806}",DEV-A2069D3A8BDC4D8E,MANUAL_KEYED,AVS_PASS,MID-698312065551,NONE,False,MOTO_PHONE,False,522,CARD_PRESENT,0100-AuthReq,12.37,1.01,114312.26,"(90, 211)",94,12,0.468,0.871,69,0.199,0,17,3.464,0.527,3.009,MOBILE_APP,0,104.110.93.66,0.1806,90.0,211.0,0.424528,0,low,2025-03-07 07:45:31,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,low,medium,medium,gt_20,low,high,1358.076290,extreme,0.158840,below_half_max,0,0,0,0,0,0,0,0,0,1,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
29,10398.83,EUR,2025-03-07 07:45:42,IVR_PHONE,CN,3228,True,"{'ip': '190.252.251.43', 'score': 0.5225}",DEV-99A395A1938A479B,QR_CODE,CVV_PASS,MID-0B52DAE47973,SIGNATURE,False,SINGLE_PURCHASE,False,558,FORCE_POST,0100-AuthReq,5.31,1.09,176955.85,"(5, 143)",101,3,0.887,0.751,54,0.189,1,39,1.866,1.445,2.348,KIOSK,0,190.252.251.43,0.5225,5.0,143.0,0.034722,0,high,2025-03-07 07:45:42,7,4,Friday,0,0,3,7,2025,morning,0.0,0,0,0,0,0,high,medium,very_high,2_5,very_low,high,1647.992076,extreme,0.058765,below_half_max,0,0,0,0,1,1,0,1,0,0,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0

====================================================================================================
train_valid_global_fraud_rate.csv

        split  fraud_rate  used_min_count
0       train    0.025471             350
1  validation    0.025200              75

====================================================================================================
validation_features_preview.csv

,amount,currency,local_timestamp,payment_channel,merchant_country,mcc,card_present,ip_risk,device_id,card_entry_mode,auth_result,merchant_id,pin_verif_method,tokenised,recurring_flag,cross_border,card_activation_age,auth_characteristics,message_type,mean_amount_30d,std_amount_30d,max_amount_30d,txn_counts,distinct_merchants_7d,distinct_countries_30d,online_share_7d,night_ratio_30d,days_since_last_txn,decline_rate_30d,chargebacks_365d,device_diversity_30d,mcc_entropy_30d,credit_util_today,spending_trend,term_location,fraud,ip_address,ip_score,txn_count_7d,txn_count_30d,txn_count_ratio_7d_30d,ip_is_private,ip_score_bin,transaction_datetime,hour,day_of_week,day_name,is_weekend,is_night_txn,month,day,year,time_period,night_unusual_score,is_night_unusual,amount_invalid_flag,std_amount_30d_zero_flag,mean_amount_30d_zero_flag,duplicate_row_flag,ip_score_risk_group,decline_rate_risk_group,credit_util_risk_group,txn_count_7d_group,txn_velocity_group,night_ratio_group,amount_to_mean_30d,amount_to_mean_group,amount_to_max_30d,amount_to_max_group,low_mcc_entropy_flag,low_night_ratio_flag,high_max_amount_30d_flag,low_spending_trend_flag,low_country_diversity_flag,high_device_diversity_flag,high_decline_rate_flag,high_ip_score_flag,night_transaction_flag,card_not_present_flag,cross_border_flag,tokenised_flag,night_unusual_group,high_ip_high_amount_flag,high_decline_high_amount_flag,private_ip_high_score_flag,high_velocity_high_amount_flag,low_mcc_entropy_x_low_night_ratio,low_mcc_entropy_x_high_max_amount_30d,low_mcc_entropy_x_low_spending_trend,low_mcc_entropy_x_card_not_present,low_night_ratio_x_high_max_amount_30d,cross_border_x_low_country_diversity,high_ip_score_x_card_not_present
0,28510.54,USD,2025-05-09 08:46:31,IVR_PHONE,ZA,3005,True,"{'ip': '4.152.77.208', 'score': 0.2561}",DEV-9586CAB37E184FCA,MAGSTRIPE,3DS_FAIL,MID-00F6D25D00AF,ONLINE_PIN,False,RECURRING_SUBSCRIPTION,False,4343,E_COMMERCE,0510-AdviceRsp,6.92,2.20,44884.36,"(22, 417)",93,21,0.851,0.314,154,0.125,0,33,1.415,0.878,1.743,POS_TERMINAL,0,4.152.77.208,0.2561,22.0,417.0,0.052632,0,medium,2025-05-09 08:46:31,8,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,medium,medium,high,gt_20,very_low,medium,3599.815657,extreme,0.635186,near_max,0,0,0,0,0,0,0,0,0,0,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
1,197532.73,USD,2025-05-09 08:46:49,SMART_WATCH,FR,7143,False,"{'ip': '170.94.54.13', 'score': 0.2408}",DEV-09F35D69B51A4FC8,MANUAL_KEYED,CVV_FAIL,MID-8A6B88CFBE24,NONE,True,INSTALLMENT_PLAN,False,3183,CARD_PRESENT,0200-FinReq,7.41,5.03,209513.70,"(37, 209)",80,9,0.665,0.823,49,0.014,0,26,2.780,0.170,0.172,BRANCH_COUNTER,0,170.94.54.13,0.2408,37.0,209.0,0.176190,0,medium,2025-05-09 08:46:49,8,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,medium,low,low,gt_20,very_low,high,23487.839477,extreme,0.942811,near_max,0,0,0,1,0,0,0,0,0,1,0,1,not_night,0,0,0,0,0,0,0,0,0,0,0
2,123399.74,USD,2025-05-09 08:47:07,SMART_WATCH,AU,3123,False,"{'ip': '133.178.205.107', 'score': 0.2424}",DEV-9C565A2F32C245DA,TOKEN_IN_APP,3DS_PASS,MID-10DDBBCB727D,NONE,True,SINGLE_PURCHASE,False,1099,FALLBACK_MAG,0200-FinReq,6.46,1.67,156270.85,"(85, 150)",78,22,0.378,0.181,154,0.324,0,38,3.074,1.044,1.535,ONLINE_PORTAL,0,133.178.205.107,0.2424,85.0,150.0,0.562914,0,medium,2025-05-09 08:47:07,8,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,medium,high,very_high,gt_20,medium,low,16541.520107,extreme,0.789648,near_max,0,0,0,0,0,1,1,0,0,1,0,1,not_night,0,0,0,0,0,0,0,0,0,0,0
3,29240.10,EUR,2025-05-09 08:47:17,WEB_BROWSER,ID,4765,False,"{'ip': '217.45.252.53', 'score': 0.1817}",DEV-5FEAB0207D604697,MANUAL_KEYED,BIOMETRIC_PASS,MID-4BE12C8042A0,SIGNATURE,True,MOTO_MAIL,False,1735,E_COMMERCE,0110-AuthRsp,10.58,1.64,222580.47,"(97, 125)",30,8,0.611,0.762,61,0.133,0,17,2.258,0.542,2.029,WEARABLE_PAY,0,217.45.252.53,0.1817,97.0,125.0,0.769841,0,low,2025-05-09 08:47:17,8,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,low,medium,medium,gt_20,medium,high,2525.051813,extreme,0.131368,below_half_max,0,0,0,0,0,0,0,0,0,1,0,1,not_night,0,0,0,0,0,0,0,0,0,0,0
4,119235.66,THB,2025-05-09 08:47:37,MOBILE_APP,AE,7003,True,"{'ip': '181.66.9.37', 'score': 0.3872}",DEV-965B2084C40447C7,MANUAL_KEYED,CVV_PASS,MID-448A3CAE77BB,NONE,True,INSTALLMENT_PLAN,False,2461,FORCE_POST,0110-AuthRsp,6.37,1.64,99774.79,"(97, 215)",28,21,0.804,0.874,170,0.163,0,6,1.672,1.147,2.751,KIOSK,0,181.66.9.37,0.3872,97.0,215.0,0.449074,0,medium,2025-05-09 08:47:37,8,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,medium,medium,very_high,gt_20,low,high,16178.515604,extreme,1.195036,above_max,0,0,0,0,0,0,0,0,0,0,0,1,not_night,0,0,0,0,0,0,0,0,0,0,0
5,76590.27,JPY,2025-05-09 08:47:53,WEB_BROWSER,GB,4306,False,"{'ip': '80.182.46.20', 'score': 0.3183}",DEV-5794ECAF2CAE40CD,QR_CODE,AVS_FAIL,MID-B5305CCB7EE5,OFFLINE_PIN,False,MOTO_PHONE,False,1999,CRYPTOGRAM_PRESENT,0400-Reversal,6.04,1.33,15133.54,"(77, 225)",66,19,0.396,0.216,118,0.152,0,28,2.374,1.356,1.302,KIOSK,0,80.182.46.20,0.3183,77.0,225.0,0.340708,0,medium,2025-05-09 08:47:53,8,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,medium,medium,very_high,gt_20,low,low,10879.299716,extreme,5.060628,extreme,0,0,0,0,0,0,0,0,0,1,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
6,160387.44,JPY,2025-05-09 08:48:32,API_SERVER,JP,5100,False,"{'ip': '103.210.174.23', 'score': 0.1375}",DEV-65551EA952F94E98,MAGSTRIPE,CVV_FAIL,MID-92C6E142335E,ONLINE_PIN,False,RECURRING_SUBSCRIPTION,False,4193,FORCE_POST,0110-AuthRsp,5.98,1.22,209254.61,"(42, 423)",104,3,0.479,0.394,130,0.235,0,2,3.208,0.505,1.415,MOBILE_APP,0,103.210.174.23,0.1375,42.0,423.0,0.099057,0,low,2025-05-09 08:48:32,8,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,low,medium,medium,gt_20,very_low,medium,22978.143266,extreme,0.766467,near_max,0,0,0,0,1,0,0,0,0,1,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
7,163905.91,USD,2025-05-09 08:48:39,SMART_WATCH,VN,3261,True,"{'ip': '6.143.146.117', 'score': 0.6513}",DEV-022DEC5CFB2143FE,MANUAL_KEYED,3DS_PASS,MID-8CDE890EEE06,NONE,True,MOTO_MAIL,False,2122,MOBILE_TOKEN,0500-Advice,15.58,3.67,105882.67,"(44, 435)",81,1,0.458,0.432,44,0.236,0,16,3.327,1.938,3.698,CALL_CENTER,0,6.143.146.117,0.6513,44.0,435.0,0.100917,0,high,2025-05-09 08:48:39,8,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,high,medium,very_high,gt_20,very_low,medium,9885.760555,extreme,1.547981,above_max,0,0,0,0,1,0,0,1,0,0,0,1,not_night,0,0,0,0,0,0,0,0,0,0,0
8,13064.13,USD,2025-05-09 08:49:45,ATM,ID,7499,False,"{'ip': '29.69.41.255', 'score': 0.2675}",DEV-98B3A4BFD7B342E2,CONTACTLESS,BIOMETRIC_PASS,MID-1D9F163B4FE8,ONLINE_PIN,True,MOTO_MAIL,True,1928,CRYPTOGRAM_PRESENT,0400-Reversal,5.76,3.18,46850.12,"(39, 455)",99,12,0.265,0.526,170,0.072,0,33,2.334,1.823,2.215,ONLINE_PORTAL,0,29.69.41.255,0.2675,39.0,455.0,0.085526,0,medium,2025-05-09 08:49:45,8,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,medium,low,very_high,gt_20,very_low,medium,1932.563609,extreme,0.278843,below_half_max,0,0,0,0,0,0,0,0,0,1,1,1,not_night,0,0,0,0,0,0,0,0,0,0,0
9,14829.11,USD,2025-05-09 08:51:29,SMART_WATCH,HK,7354,False,"{'ip': '224.224.202.73', 'score': 0.4764}",DEV-9B9E8838553D4FC0,MAGSTRIPE,3DS_FAIL,MID-8803BD6BF7F1,SIGNATURE,False,MOTO_MAIL,False,2695,MOBILE_TOKEN,0100-AuthReq,5.32,8.75,141580.87,"(72, 497)",47,23,0.776,0.095,105,0.197,2,17,2.827,1.001,4.542,WEARABLE_PAY,0,224.224.202.73,0.4764,72.0,497.0,0.144578,0,medium,2025-05-09 08:51:29,8,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,medium,medium,very_high,gt_20,very_low,very_low,2346.378165,extreme,0.104739,below_half_max,0,1,0,0,0,0,0,0,0,1,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
10,160969.10,USD,2025-05-09 08:52:26,SMART_WATCH,IN,5558,False,"{'ip': '159.22.86.139', 'score': 0.3926}",DEV-E0F5AD6B86644053,MANUAL_KEYED,AVS_PASS,MID-A564213A192F,OFFLINE_PIN,True,MOTO_PHONE,False,1036,MOBILE_TOKEN,0200-FinReq,8.36,1.63,188657.47,"(33, 338)",76,10,0.164,0.011,87,0.152,0,12,3.577,1.035,1.695,KIOSK,0,159.22.86.139,0.3926,33.0,338.0,0.097345,0,medium,2025-05-09 08:52:26,8,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,medium,medium,very_high,gt_20,very_low,very_low,17197.553419,extreme,0.853230,near_max,0,1,0,0,0,0,0,0,0,1,0,1,not_night,0,0,0,0,0,0,0,0,0,0,0
11,198608.49,GBP,2025-05-09 08:53:47,SMART_WATCH,MY,5094,False,"{'ip': '41.239.242.117', 'score': 0.111}",DEV-5ED6B2C7F51C413D,MANUAL_KEYED,3DS_FAIL,MID-B6C847996E48,OFFLINE_PIN,False,RECURRING_SUBSCRIPTION,False,3650,FORCE_POST,0400-Reversal,9.20,1.30,81234.60,"(20, 322)",51,7,0.091,0.375,104,0.231,0,6,2.176,0.055,0.761,MOBILE_APP,0,41.239.242.117,0.1110,20.0,322.0,0.061920,0,low,2025-05-09 08:53:47,8,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,low,medium,low,11_20,very_low,medium,19471.420588,extreme,2.444845,much_above_max,0,0,0,0,0,0,0,0,0,1,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
12,187926.26,USD,2025-05-09 08:54:12,SMART_WATCH,JP,7702,True,"{'ip': '130.243.134.214', 'score': 0.3519}",DEV-C7FBDB03EA1D4F04,MAGSTRIPE,AVS_PASS,MID-EAEEAE2E910F,SIGNATURE,True,MOTO_MAIL,False,2092,FALLBACK_MAG,0420-RepeatRev,5.30,1.57,52870.46,"(58, 165)",110,2,0.502,0.772,57,0.148,0,35,2.671,1.851,1.351,BRANCH_COUNTER,0,130.243.134.214,0.3519,58.0,165.0,0.349398,0,medium,2025-05-09 08:54:12,8,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,medium,medium,very_high,gt_20,low,high,29829.565079,extreme,3.554399,much_above_max,0,0,0,0,1,0,0,0,0,0,0,1,not_night,0,0,0,0,0,0,0,0,0,0,0
13,135550.34,USD,2025-05-09 08:54:15,WEB_BROWSER,SG,7768,True,"{'ip': '23.206.246.58', 'score': 0.4091}",DEV-962E53FFFC2744A6,MAGSTRIPE,BIOMETRIC_FAIL,MID-BB82DB3886A0,NONE,False,SINGLE_PURCHASE,False,3764,CARD_PRESENT,0110-AuthRsp,11.41,1.13,59992.70,"(49, 152)",85,2,0.107,0.449,113,0.046,0,27,1.660,0.965,4.432,KIOSK,0,23.206.246.58,0.4091,49.0,152.0,0.320261,0,medium,2025-05-09 08:54:15,8,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,medium,low,very_high,gt_20,low,medium,10922.670427,extreme,2.259410,much_above_max,0,0,0,0,1,0,0,0,0,0,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
14,46115.80,USD,2025-05-09 08:55:08,POS_TERMINAL,JP,4521,True,"{'ip': '70.92.39.251', 'score': 0.3572}",DEV-FE16392F955C472C,MANUAL_KEYED,BIOMETRIC_PASS,MID-0A257119F68E,ONLINE_PIN,False,MOTO_PHONE,False,561,E_COMMERCE,0200-FinReq,5.83,6.06,82244.51,"(93, 180)",86,10,0.521,0.836,155,0.227,0,8,1.781,0.644,0.738,BRANCH_COUNTER,0,70.92.39.251,0.3572,93.0,180.0,0.513812,0,medium,2025-05-09 08:55:08,8,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,medium,medium,high,gt_20,medium,high,6751.947291,extreme,0.560709,near_max,0,0,0,0,0,0,0,0,0,0,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
15,38838.38,USD,2025-05-09 08:57:48,IVR_PHONE,AU,3185,False,"{'ip': '124.195.60.197', 'score': 0.1139}",DEV-84F650E7E09845D4,CHIP,AVS_FAIL,MID-CC1E8A82F9EA,SIGNATURE,False,INSTALLMENT_PLAN,False,1777,CARD_PRESENT,0110-AuthRsp,6.02,7.26,221418.44,"(94, 244)",90,4,0.264,0.505,14,0.088,0,20,1.713,1.282,3.880,ONLINE_PORTAL,0,124.195.60.197,0.1139,94.0,244.0,0.383673,0,low,2025-05-09 08:57:48,8,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,low,low,very_high,gt_20,low,medium,5532.532764,extreme,0.175406,below_half_max,0,0,0,0,0,0,0,0,0,1,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
16,121619.53,AUD,2025-05-09 08:58:55,IVR_PHONE,DE,7050,True,"{'ip': '1.110.58.124', 'score': 0.2137}",DEV-7065E1642FAA4792,MAGSTRIPE,3DS_FAIL,MID-6625FB18DC06,NONE,True,SINGLE_PURCHASE,False,3161,FORCE_POST,0200-FinReq,11.67,1.14,10114.78,"(43, 466)",76,10,0.149,0.642,120,0.066,0,3,2.520,1.699,3.890,KIOSK,0,1.110.58.124,0.2137,43.0,466.0,0.092077,0,medium,2025-05-09 08:58:55,8,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,medium,low,very_high,gt_20,very_low,high,9599.015785,extreme,12.022754,extreme,0,0,0,0,0,0,0,0,0,0,0,1,not_night,0,0,0,0,0,0,0,0,0,0,0
17,135906.54,USD,2025-05-09 08:59:46,POS_TERMINAL,CA,4149,False,"{'ip': '90.28.179.132', 'score': 0.2751}",DEV-D2D1B054839341C2,MAGSTRIPE,AVS_FAIL,MID-0047F4A00DA6,SIGNATURE,False,RECURRING_SUBSCRIPTION,False,4194,FALLBACK_MAG,0110-AuthRsp,5.77,1.79,89167.49,"(65, 265)",117,11,0.157,0.527,154,0.056,0,15,3.485,1.030,2.151,POS_TERMINAL,0,90.28.179.132,0.2751,65.0,265.0,0.244361,0,medium,2025-05-09 08:59:46,8,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,medium,low,very_high,gt_20,low,medium,20074.821270,extreme,1.524154,above_max,0,0,0,0,0,0,0,0,0,1,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
18,27270.95,KRW,2025-05-09 09:00:07,WEB_BROWSER,SG,5054,True,"{'ip': '78.93.200.123', 'score': 0.3024}",DEV-111351A3A5FF40D1,CONTACTLESS,CVV_PASS,MID-462B59C74022,NONE,True,MOTO_MAIL,False,2961,MOBILE_TOKEN,0200-FinReq,9.73,1.13,158908.51,"(91, 146)",34,23,0.321,0.504,158,0.126,0,6,1.154,1.868,3.175,KIOSK,0,78.93.200.123,0.3024,91.0,146.0,0.619048,0,medium,2025-05-09 09:00:07,9,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,medium,medium,very_high,gt_20,medium,medium,2541.561044,extreme,0.171613,below_half_max,0,0,0,0,0,0,0,0,0,0,0,1,not_night,0,0,0,0,0,0,0,0,0,0,0
19,23275.69,USD,2025-05-09 09:01:00,MOBILE_APP,AU,4983,True,"{'ip': '67.241.88.152', 'score': 0.3749}",DEV-770166D0D3A44251,TOKEN_IN_APP,3DS_FAIL,MID-DA1E9EF99302,NONE,True,RECURRING_SUBSCRIPTION,False,4274,FORCE_POST,0110-AuthRsp,6.60,3.86,132764.81,"(11, 21)",11,22,0.694,0.813,130,0.158,0,2,3.651,1.424,2.748,CALL_CENTER,0,67.241.88.152,0.3749,11.0,21.0,0.500000,0,medium,2025-05-09 09:01:00,9,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,medium,medium,very_high,11_20,low,high,3062.590789,extreme,0.175314,below_half_max,0,0,0,0,0,0,0,0,0,0,0,1,not_night,0,0,0,0,0,0,0,0,0,0,0
20,192114.67,AUD,2025-05-09 09:01:39,IVR_PHONE,IN,7847,False,"{'ip': '210.106.253.239', 'score': 0.2959}",DEV-FF81E1C64C974A42,MAGSTRIPE,AVS_FAIL,MID-E5DBE9FA220A,SIGNATURE,True,INSTALLMENT_PLAN,False,4041,E_COMMERCE,0200-FinReq,5.27,2.50,10642.20,"(11, 131)",4,18,0.844,0.552,41,0.087,0,18,0.315,1.663,0.200,CALL_CENTER,0,210.106.253.239,0.2959,11.0,131.0,0.083333,0,medium,2025-05-09 09:01:39,9,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,medium,low,very_high,11_20,very_low,medium,30640.298246,extreme,18.050461,extreme,1,0,0,1,0,0,0,0,0,1,0,1,not_night,0,0,0,0,0,0,1,1,0,0,0
21,131930.22,USD,2025-05-09 09:03:01,SMART_WATCH,BR,3135,False,"{'ip': '69.215.85.14', 'score': 0.5659}",DEV-629401B3108C4552,CHIP,CVV_FAIL,MID-25D9A02B3D91,SIGNATURE,False,INSTALLMENT_PLAN,False,3772,CARD_PRESENT,0500-Advice,5.98,2.12,116911.76,"(10, 229)",58,13,0.594,0.353,160,0.202,0,29,0.235,1.270,4.739,BRANCH_COUNTER,0,69.215.85.14,0.5659,10.0,229.0,0.043478,0,high,2025-05-09 09:03:01,9,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,high,medium,very_high,6_10,very_low,medium,18901.177650,extreme,1.128450,above_max,1,0,0,0,0,0,0,1,0,1,0,0,not_night,0,0,0,0,0,0,0,1,0,0,1
22,51269.51,HKD,2025-05-09 09:03:20,MOBILE_APP,CA,3304,False,"{'ip': '142.139.76.222', 'score': 0.1734}",DEV-879D59FE29AA4205,CHIP,AVS_PASS,MID-A562904D89C3,NONE,False,MOTO_PHONE,False,2124,CARD_PRESENT,0400-Reversal,14.59,1.30,33165.26,"(86, 333)",51,12,0.761,0.471,122,0.284,0,40,3.441,0.046,3.501,KIOSK,0,142.139.76.222,0.1734,86.0,333.0,0.257485,0,low,2025-05-09 09:03:20,9,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,low,medium,low,gt_20,low,medium,3288.615138,extreme,1.545833,above_max,0,0,0,0,0,1,1,0,0,1,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
23,59817.01,EUR,2025-05-09 09:07:05,ATM,HK,3182,False,"{'ip': '36.212.94.92', 'score': 0.3513}",DEV-B4AA79E48E054BBA,QR_CODE,CVV_PASS,MID-ACC3A7CC683A,ONLINE_PIN,True,SINGLE_PURCHASE,False,2270,FORCE_POST,0500-Advice,6.40,2.04,159983.37,"(22, 47)",5,14,0.257,0.475,47,0.155,0,6,0.464,1.730,0.921,BRANCH_COUNTER,0,36.212.94.92,0.3513,22.0,47.0,0.458333,0,medium,2025-05-09 09:07:05,9,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,medium,medium,very_high,gt_20,low,medium,8083.379730,extreme,0.373893,below_half_max,0,0,0,0,0,0,0,0,0,1,0,1,not_night,0,0,0,0,0,0,0,0,0,0,0
24,67220.55,USD,2025-05-09 09:09:39,SMART_WATCH,BR,3224,False,"{'ip': '104.136.45.5', 'score': 0.5896}",DEV-26D31A2F109A4C80,MANUAL_KEYED,3DS_FAIL,MID-6DD29DFA75FD,NONE,False,INSTALLMENT_PLAN,True,4198,CRYPTOGRAM_PRESENT,0100-AuthReq,10.10,1.12,218204.61,"(55, 199)",74,18,0.896,0.755,47,0.056,0,35,0.419,0.796,3.619,MOBILE_APP,0,104.136.45.5,0.5896,55.0,199.0,0.275000,0,high,2025-05-09 09:09:39,9,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,high,low,high,gt_20,low,high,6055.905405,extreme,0.308061,below_half_max,0,0,0,0,0,0,0,1,0,1,1,0,not_night,0,0,0,0,0,0,0,0,0,0,1
25,139087.36,SGD,2025-05-09 09:10:46,WEB_BROWSER,DE,5727,True,"{'ip': '50.175.76.154', 'score': 0.3567}",DEV-F2E9B4FC7C2E4364,MAGSTRIPE,CVV_FAIL,MID-92BE4190D0C2,SIGNATURE,False,MOTO_MAIL,False,3553,E_COMMERCE,0510-AdviceRsp,7.04,1.53,40338.61,"(96, 441)",69,7,0.789,0.526,117,0.170,3,33,2.860,0.719,4.292,POS_TERMINAL,0,50.175.76.154,0.3567,96.0,441.0,0.217195,0,medium,2025-05-09 09:10:46,9,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,medium,medium,high,gt_20,low,medium,17299.422886,extreme,3.447910,much_above_max,0,0,0,0,0,0,0,0,0,0,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
26,108926.35,HKD,2025-05-09 09:13:24,IVR_PHONE,AU,7951,False,"{'ip': '94.102.82.160', 'score': 0.2354}",DEV-11E4D59AE45F4A74,MANUAL_KEYED,CVV_FAIL,MID-16424870B3E4,ONLINE_PIN,True,MOTO_PHONE,False,2823,MOBILE_TOKEN,0110-AuthRsp,8.18,18.32,180007.79,"(29, 95)",110,9,0.558,0.084,131,0.226,0,37,2.183,1.644,0.528,MOBILE_APP,0,94.102.82.160,0.2354,29.0,95.0,0.302083,0,medium,2025-05-09 09:13:24,9,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,medium,medium,very_high,gt_20,low,very_low,11865.615468,extreme,0.605117,near_max,0,1,0,1,0,1,0,0,0,1,0,1,not_night,0,0,0,0,0,0,0,0,0,0,0
27,90052.27,USD,2025-05-09 09:14:12,SMART_WATCH,CA,3209,False,"{'ip': '74.72.212.133', 'score': 0.0922}",DEV-4A36CB693AF044B6,MAGSTRIPE,AVS_FAIL,MID-0CB0ADEDCCA0,SIGNATURE,False,RECURRING_SUBSCRIPTION,False,849,E_COMMERCE,0110-AuthRsp,5.45,1.25,170645.03,"(10, 55)",16,13,0.585,0.099,117,0.097,0,12,2.603,1.633,3.925,BRANCH_COUNTER,0,74.72.212.133,0.0922,10.0,55.0,0.178571,0,low,2025-05-09 09:14:12,9,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,low,low,very_high,6_10,very_low,very_low,13961.592248,extreme,0.527714,near_max,0,1,0,0,0,0,0,0,0,1,0,0,not_night,0,0,0,0,0,0,0,0,0,0,0
28,95484.27,SGD,2025-05-09 09:18:36,SMART_WATCH,CA,7433,False,"{'ip': '81.167.249.222', 'score': 0.2945}",DEV-3A8F3CB5274F47AB,MAGSTRIPE,3DS_PASS,MID-17C479F47846,SIGNATURE,False,RECURRING_SUBSCRIPTION,True,3344,FORCE_POST,0510-AdviceRsp,5.52,1.13,5593.48,"(32, 263)",113,13,0.866,0.996,137,0.158,0,34,1.514,1.474,0.792,BRANCH_COUNTER,0,81.167.249.222,0.2945,32.0,263.0,0.121212,0,medium,2025-05-09 09:18:36,9,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,medium,medium,very_high,gt_20,very_low,high,14644.826687,extreme,17.067586,extreme,0,0,0,0,0,0,0,0,0,1,1,0,not_night,0,0,0,0,0,0,0,0,0,0,0
29,87198.84,EUR,2025-05-09 09:20:41,IVR_PHONE,CA,3058,False,"{'ip': '193.81.93.67', 'score': 0.2202}",DEV-E990171197A546A9,MANUAL_KEYED,3DS_PASS,MID-9DDB61F0BA9D,ONLINE_PIN,False,SINGLE_PURCHASE,False,2187,MOBILE_TOKEN,0420-RepeatRev,5.67,1.05,141552.10,"(96, 175)",58,19,0.575,0.835,78,0.131,0,21,0.384,1.483,2.612,WEARABLE_PAY,0,193.81.93.67,0.2202,96.0,175.0,0.545455,0,medium,2025-05-09 09:20:41,9,4,Friday,0,0,5,9,2025,morning,0.0,0,0,0,0,0,medium,medium,very_high,gt_20,medium,high,13073.289355,extreme,0.616015,near_max,1,0,0,0,0,0,0,0,0,1,0,0,not_night,0,0,0,0,0,0,0,1,0,0,0

In [4]:
for md_file in [
    REPORT_DIR / "insight_report.md",
    REPORT_DIR / "insight_stability_report.md",
    PROJECT_ROOT / "reports" / "insight_report.md",
    PROJECT_ROOT / "reports" / "insight_stability_report.md",
]:
    if md_file.exists():
        print("\n" + "=" * 100)
        print(md_file)
        print(md_file.read_text(encoding="utf-8")[:5000])

====================================================================================================
e:\fraud-detection-project\reports\insight_report.md

# Fraud Detection - Hidden Insight Mining Report

## 1. Tổng quan

- Fraud rate toàn bộ dataset: **0.0255 (2.55%)**
- Mục tiêu giai đoạn này là tìm segment/rule có fraud rate cao hơn baseline, sau đó chuyển các pattern có ý nghĩa thành feature cho model.

## 2. Segment nghiệp vụ nổi bật

| segment_name           |   support |   support_rate |   fraud_count |   fraud_rate |     lift | strength   | description                                                                                                                         |
|:-----------------------|----------:|---------------:|--------------:|-------------:|---------:|:-----------|:------------------------------------------------------------------------------------------------------------------------------------|
| very_low_mcc_entropy   |      3510 |      0.0501429 |           339 |    0.0965812 | 3.79175  | STRONG     | Nhóm cực thấp về mcc_entropy_30d, thường cần soi kỹ hơn.                                                                            |
| low_mcc_entropy        |      7009 |      0.100129  |           625 |    0.0891711 | 3.50083  | STRONG     | User có lịch sử MCC ít đa dạng. Đây là tín hiệu behavioral anomaly vì giao dịch mới có thể lệch khỏi hành vi ngành hàng quen thuộc. |
| low_night_ratio        |      7038 |      0.100543  |           511 |    0.0726059 | 2.85048  | MEDIUM     | User gần như không có thói quen giao dịch ban đêm.                                                                                  |
| night_unusual          |      2401 |      0.0343    |           171 |    0.0712203 | 2.79609  | MEDIUM     | Giao dịch ban đêm nhưng user có lịch sử night_ratio_30d thấp. Đây là tín hiệu bất thường về thời gian.                              |
| high_max_amount_30d    |      7000 |      0.1       |           439 |    0.0627143 | 2.46214  | MEDIUM     | User có max_amount_30d thuộc nhóm rất cao.                                                                                          |
| low_country_diversity  |      8464 |      0.120914  |           525 |    0.0620274 | 2.43518  | MEDIUM     | User có lịch sử giao dịch ở ít quốc gia.                                                                                            |
| has_chargeback_history |     10439 |      0.149129  |           306 |    0.0293132 | 1.15082  | LOW_SIGNAL | User có lịch sử chargeback trong 365 ngày.                                                                                          |
| card_not_present       |     45672 |      0.652457  |          1201 |    0.0262962 | 1.03238  | LOW_SIGNAL | Giao dịch không có thẻ vật lý, thường rủi ro hơn trong fraud online.                                                                |
| night_transaction      |     23339 |      0.333414  |           611 |    0.0261794 | 1.02779  | LOW_SIGNAL | Giao dịch hiện tại xảy ra ban đêm.                                                                                                  |
| tokenised_transaction  |     31516 |      0.450229  |           784 |    0.0248763 | 0.976634 | LOW_SIGNAL | Giao dịch tokenised.                                                                                                                |
| high_current_amount    |      7000 |      0.1       |           173 |    0.0247143 | 0.970275 | LOW_SIGNAL | Giao dịch hiện tại có amount thuộc nhóm cao.                                                                                        |
| high_ip_score          |      7001 |      0.100014  |           172 |    0.0245679 | 0.964529 | LOW_SIGNAL | IP risk score thuộc nhóm cao.                                                                                                       |
| high_amount_to_mean    |      7000 |      0.1       |           147 |    0.021     | 0.824453 | LOW_SIGNAL | Amount hiện tại cao hơn nhiều so với mean_amount_30d. Đây là tín hiệu amount anomaly.                                               |
| cross_border           |     13963 |      0.199471  |           280 |    0.020053  | 0.787274 | LOW_SIGNAL | Giao dịch xuyên biên giới.                                                                                                          |
| high_device_diversity  |      8633 |      0.123329  |           125 |    0.0144793 | 0.568454 | LOW_SIGNAL | User dùng nhiều thiết bị trong 30 ngày. Có thể liên quan account takeover hoặc account sharing.                                     |

## 3. Interaction nghiệp vụ ưu tiên

| rule                                                        |   support |   support_rate |   fraud_count |   fraud_rate |      lift | strength    | business_interpretation                                                                                                                                                     |
|:------------------------------------------------------------|----------:|---------------:|--------------:|-------------:|----------:|:------------|:----------------------------------

====================================================================================================
e:\fraud-detection-project\reports\insight_stability_report.md
# Fraud Insight Stability Check Report

## 1. Split summary

| split      |   rows |   fraud_count |   non_fraud_count |   fraud_rate | start_time          | end_time            | split_strategy   |
|:-----------|-------:|--------------:|------------------:|-------------:|:--------------------|:--------------------|:-----------------|
| train      |  70000 |          1783 |             68217 |    0.0254714 | 2025-03-07 07:19:19 | 2025-05-09 08:45:13 | time             |
| validation |  15000 |           378 |             14622 |    0.0252    | 2025-05-09 08:46:31 | 2025-05-22 21:09:42 | time             |
| test       |  15000 |           388 |             14612 |    0.0258667 | 2025-05-22 21:09:58 | 2025-06-05 07:17:23 | time             |

## 2. Stable numeric patterns

| feature                | bin                      |   count_train |   fraud_count_train |   fraud_rate_train |   global_fraud_rate_train |   fraud_rate_diff_train |   lift_train |   count_valid |   fraud_count_valid |   fraud_rate_valid |   global_fraud_rate_valid |   fraud_rate_diff_valid |   lift_valid |   lift_diff_valid_train |   lift_ratio_valid_train |   fraud_rate_diff_valid_train |
|:-----------------------|:-------------------------|--------------:|--------------------:|-------------------:|--------------------------:|------------------------:|-------------:|--------------:|--------------------:|-------------------:|--------------------------:|------------------------:|-------------:|------------------------:|-------------------------:|------------------------------:|
| max_amount_30d         | (225176.777, inf]        |          7000 |                 439 |          0.0627143 |                 0.0254714 |               0.0372429 |      2.46214 |          1444 |                 115 |          0.0796399 |                    0.0252 |               0.0544399 |      3.16031 |               0.698171  |                 1.28356  |                   0.0169256   |
| mcc_entropy_30d        | (-inf, 0.393]            |          7009 |                 625 |          0.0891711 |                 0.0254714 |               0.0636996 |      3.50083 |          1525 |                 112 |          0.0734426 |                    0.0252 |               0.0482426 |      2.91439 |              -0.586437  |                 0.832486 |                  -0.0157284   |
| night_ratio_30d        | (-inf, 0.101]            |          7038 |                 511 |          0.0726059 |                 0.0254714 |               0.0471344 |      2.85048 |          1531 |                 111 |          0.0725016 |                    0.0252 |               0.0473016 |      2.87705 |               0.0265667 |                 1.00932  |                  -0.000104221 |
| spending_trend         | (-inf, 0.584]            |          7002 |                 463 |          0.066124  |                 0.0254714 |               0.0406525 |      2.59601 |          1400 |                  89 |          0.0635714 |                    0.0252 |               0.0383714 |      2.52268 |              -0.0733296 |                 0.971753 |                  -0.00255254  |
| distinct_countries_30d | (-inf, 3.0]              |          8464 |                 525 |          0.0620274 |                 0.0254714 |               0.036556  |      2.43518 |          1842 |                 114 |          0.0618893 |                    0.0252 |               0.0366893 |      2.45592 |               0.0207467 |                 1.00852  |                  -0.000138159 |
| mcc_entropy_30d        | (0.393, 0.788]           |          6992 |                 413 |          0.0590675 |                 0.0254714 |               0.0335961 |      2.31897 |          1405 |                  85 |          0.0604982 |                    0.0252 |               0.0352982 |      2.40072 |               0.081752  |                 1.03525  |                   0.00143071  |
| night_unusual_score    | (0.705, inf]             |          6991 |                 381 |          0.0544986 |                 0.0254714 |               0.0290272 |      2.1396  |          1410 |                  84 |          0.0595745 |                    0.0252 |               0.0343745 |      2.36407 |               0.224467  |                 1.10491  |                   0.00507583  |
| spending_trend         | (0.584, 1.073]           |          7008 |                 331 |          0.0472317 |                 0.0254714 |               0.0217603 |      1.8543  |          1522 |                  81 |          0.0532194 |                    0.0252 |               0.0280194 |      2.11188 |               0.25758   |                 1.13891  |                   0.00598771  |
| std_amount_30d         | (1.12, 1.25]             |          6710 |                 292 |          0.0435171 |                 0.0254714 |               0.0180457 |      1.70847 |          1392 |                  73 |          0.0524425 |                    0.0252

In [5]:
selected_insights = pd.DataFrame([
    {
        "insight": "low_mcc_entropy",
        "business_meaning": "User có lịch sử ngành hàng/MCC ít đa dạng.",
        "feature_action": "Giữ mcc_entropy_30d, tạo low_mcc_entropy_flag/very_low_mcc_entropy_flag.",
        "expected_model_effect": "Entropy thấp làm tăng fraud risk.",
    },
    {
        "insight": "low_night_ratio",
        "business_meaning": "User ít có lịch sử giao dịch ban đêm.",
        "feature_action": "Giữ night_ratio_30d, tạo low_night_ratio_flag, night_unusual_score.",
        "expected_model_effect": "Giao dịch ban đêm bất thường làm tăng fraud risk.",
    },
    {
        "insight": "amount_anomaly",
        "business_meaning": "Amount hiện tại lệch khỏi lịch sử user.",
        "feature_action": "Tạo amount_z_30d, amount_to_mean_30d, log_amount_to_max_30d.",
        "expected_model_effect": "Amount anomaly cao làm tăng fraud risk.",
    },
    {
        "insight": "low_spending_trend",
        "business_meaning": "Xu hướng chi tiêu thấp/bất thường.",
        "feature_action": "Giữ spending_trend, tạo low_spending_trend_flag.",
        "expected_model_effect": "Spending trend thấp có thể làm tăng risk.",
    },
    {
        "insight": "low_country_diversity",
        "business_meaning": "Lịch sử quốc gia ít đa dạng.",
        "feature_action": "Giữ distinct_countries_30d, tạo low_country_diversity_flag.",
        "expected_model_effect": "Country diversity thấp làm tăng risk.",
    },
])

display(selected_insights)

                 insight                            business_meaning                                     feature_action                              expected_model_effect
0        low_mcc_entropy  User có lịch sử ngành hàng/MCC ít đa dạng.  Giữ mcc_entropy_30d, tạo low_mcc_entropy_flag/...                  Entropy thấp làm tăng fraud risk.
1        low_night_ratio       User ít có lịch sử giao dịch ban đêm.  Giữ night_ratio_30d, tạo low_night_ratio_flag,...  Giao dịch ban đêm bất thường làm tăng fraud risk.
2         amount_anomaly     Amount hiện tại lệch khỏi lịch sử user.  Tạo amount_z_30d, amount_to_mean_30d, log_amou...            Amount anomaly cao làm tăng fraud risk.
3     low_spending_trend          Xu hướng chi tiêu thấp/bất thường.   Giữ spending_trend, tạo low_spending_trend_flag.          Spending trend thấp có thể làm tăng risk.
4  low_country_diversity                Lịch sử quốc gia ít đa dạng.  Giữ distinct_countries_30d, tạo low_country_di...              Country diversity thấp làm tăng risk.

## Kết luận cần ghi sau khi chạy

            - Insight nào ổn định trên train/validation?
            - Insight nào đã chuyển thành feature?
            - Feature nào cần cẩn thận leakage?