# 05 - Feature Engineering Experiment

            Mục tiêu:

            - Kiểm tra output giai đoạn feature engineering.
            - Kiểm tra feature metadata.
            - Kiểm tra train/validation/test split.
            - Kiểm tra missing/correlation để đảm bảo data sẵn sàng train model.

In [1]:
from pathlib import Path
import sys
import json

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.append(str(PROJECT_ROOT))

pd.set_option("display.max_columns", 300)
pd.set_option("display.width", 200)

print("PROJECT_ROOT:", PROJECT_ROOT)

PROJECT_ROOT: e:\fraud-detection-project

In [2]:
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

train_path = PROCESSED_DIR / "model_train_features.parquet"
val_path = PROCESSED_DIR / "model_validation_features.parquet"
test_path = PROCESSED_DIR / "model_test_features.parquet"
metadata_path = PROCESSED_DIR / "feature_metadata.json"

for path in [train_path, val_path, test_path, metadata_path]:
    print(path, path.exists())

e:\fraud-detection-project\data\processed\model_train_features.parquet True
e:\fraud-detection-project\data\processed\model_validation_features.parquet True
e:\fraud-detection-project\data\processed\model_test_features.parquet True
e:\fraud-detection-project\data\processed\feature_metadata.json True

In [3]:
train_df = pd.read_parquet(train_path)
val_df = pd.read_parquet(val_path)
test_df = pd.read_parquet(test_path)

print("Train:", train_df.shape)
print("Validation:", val_df.shape)
print("Test:", test_df.shape)

display(train_df.head(3).T.rename(columns=lambda i: f"row_{i}"))

Train: (70000, 59)
Validation: (15000, 59)
Test: (15000, 59)

                                                                 row_0               row_1                   row_2
night_ratio_30d                                                   0.76               0.236                   0.099
mcc_entropy_30d                                                  2.124               1.742                    2.48
distinct_merchants_7d                                               21                 120                       1
distinct_countries_30d                                              10                  20                       5
device_diversity_30d                                                32                  24                       3
decline_rate_30d                                                 0.282               0.095                   0.101
chargebacks_365d                                                     0                   0                       0
credit_util_today                                                1.452               0.328                   1.486
spending_trend                                                   4.548               4.655                   3.255
ip_score                                                        0.3064              0.4186                   0.171
txn_count_7d                                                      48.0                11.0                    72.0
txn_count_30d                                                     69.0                13.0                   156.0
txn_count_ratio_7d_30d                                        0.685714            0.785714                0.458599
hour                                                                 7                   7                       7
log_mean_amount_30d                                           2.047693            2.634762                1.842136
amount_to_mean_30d                                         9211.047742         3009.952654            24385.377179
log_amount_to_max_30d                                         0.289326            0.167347                0.737693
amount_z_30d                                              29741.195833        14123.164983            70580.926606
night_unusual_score                                                0.0                 0.0                     0.0
currency                                                           GBP                 EUR                     USD
payment_channel                                             MOBILE_APP          API_SERVER             WEB_BROWSER
merchant_country                                                    PH                  IN                      ZA
mcc                                                               7765                7995                    3038
card_entry_mode                                            CONTACTLESS        TOKEN_IN_APP             CONTACTLESS
auth_result                                                   CVV_PASS            3DS_PASS                3DS_FAIL
pin_verif_method                                                  NONE           SIGNATURE              ONLINE_PIN
recurring_flag                                               MOTO_MAIL          MOTO_PHONE  RECURRING_SUBSCRIPTION
auth_characteristics                                CRYPTOGRAM_PRESENT  CRYPTOGRAM_PRESENT      CRYPTOGRAM_PRESENT
message_type                                               0200-FinReq         0200-FinReq           0400-Reversal
term_location                                              CALL_CENTER       ONLINE_PORTAL            WEARABLE_PAY
day_name                                                        Friday              Friday                  Friday
time_period                                                    morning             morning                 morning
night_ratio_group                                                 high                 low                very_low
night_unusual_group                                          not_night           not_night               not_night
amount_to_max_group                                     below_half_max      below_half_max               above_max
ip_score_risk_group                                             medium              medium                     low
decline_rate_risk_group                                         medium                 low                  medium
credit_util_risk_group                                       very_high              medium               very_high
txn_count_7d_group                                               gt_20               11_20                   gt_20
txn_velocity_group                                              medium              medium                     low
very_low_mcc_entropy_flag                                            0                   0                       0
low_mcc_entropy_flag                                                 0                   0                       0
low_night_ratio_flag                                                 0                   0                       1
high_max_amount_30d_flag                                             0                   1                       0
low_spending_trend_flag                                              0                   0                       0
low_country_diversity_flag                                           0                   0                       0
night_transaction_flag                                               0                   0                       0
card_not_present_flag                                                1                   0                       1
cross_border_flag                                                    0                   1                       0
tokenised_flag                                                       0                   1                       0
low_mcc_entropy_x_low_night_ratio                                    0                   0                       0
low_mcc_entropy_x_low_night_ratio_x_card_not_pr...                   0                   0                       0
low_mcc_entropy_x_high_max_amount_30d                                0                   0                       0
low_mcc_entropy_x_low_spending_trend                                 0                   0                       0
low_night_ratio_x_high_max_amount_30d                                0                   0                       0
low_night_ratio_x_night_transaction                                  0                   0                       0
low_mcc_entropy_x_card_not_present                                   0                   0                       0
cross_border_x_low_country_diversity                                 0                   0                       0
fraud                                                                0                   0                       0

In [4]:
with open(metadata_path, "r", encoding="utf-8") as f:
    metadata = json.load(f)

for key in ["numeric_features", "categorical_features", "binary_features", "interaction_features"]:
    print("\n" + "=" * 100)
    values = metadata.get(key, [])
    print(key, len(values))
    print(values[:15])
    if len(values) > 15:
        print(f"... {len(values) - 15} more")

====================================================================================================
numeric_features 19
['night_ratio_30d', 'mcc_entropy_30d', 'distinct_merchants_7d', 'distinct_countries_30d', 'device_diversity_30d', 'decline_rate_30d', 'chargebacks_365d', 'credit_util_today', 'spending_trend', 'ip_score', 'txn_count_7d', 'txn_count_30d', 'txn_count_ratio_7d_30d', 'hour', 'log_mean_amount_30d']
... 4 more

====================================================================================================
categorical_features 21
['currency', 'payment_channel', 'merchant_country', 'mcc', 'card_entry_mode', 'auth_result', 'pin_verif_method', 'recurring_flag', 'auth_characteristics', 'message_type', 'term_location', 'day_name', 'time_period', 'night_ratio_group', 'night_unusual_group']
... 6 more

====================================================================================================
binary_features 10
['very_low_mcc_entropy_flag', 'low_mcc_entropy_flag', 'low_night_ratio_flag', 'high_max_amount_30d_flag', 'low_spending_trend_flag', 'low_country_diversity_flag', 'night_transaction_flag', 'card_not_present_flag', 'cross_border_flag', 'tokenised_flag']

====================================================================================================
interaction_features 8
['low_mcc_entropy_x_low_night_ratio', 'low_mcc_entropy_x_low_night_ratio_x_card_not_present', 'low_mcc_entropy_x_high_max_amount_30d', 'low_mcc_entropy_x_low_spending_trend', 'low_night_ratio_x_high_max_amount_30d', 'low_night_ratio_x_night_transaction', 'low_mcc_entropy_x_card_not_present', 'cross_border_x_low_country_diversity']

In [5]:
for name, d in [("train", train_df), ("validation", val_df), ("test", test_df)]:
    print("\n" + "=" * 100)
    print(name)
    target_dist = d["fraud"].value_counts(normalize=True).rename("ratio").reset_index()
    display(target_dist)

====================================================================================================
train

   fraud     ratio
0      0  0.974529
1      1  0.025471

====================================================================================================
validation

   fraud   ratio
0      0  0.9748
1      1  0.0252

====================================================================================================
test

   fraud     ratio
0      0  0.974133
1      1  0.025867

In [6]:
all_features = metadata["all_model_features"]

missing = (
    train_df[all_features]
    .isna()
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)
missing.columns = ["feature", "missing_rate"]
display(missing.head(40))

                    feature  missing_rate
0           night_ratio_30d           0.0
1           mcc_entropy_30d           0.0
2     distinct_merchants_7d           0.0
3    distinct_countries_30d           0.0
4      device_diversity_30d           0.0
5          decline_rate_30d           0.0
6          chargebacks_365d           0.0
7         credit_util_today           0.0
8            spending_trend           0.0
9                  ip_score           0.0
10             txn_count_7d           0.0
11            txn_count_30d           0.0
12   txn_count_ratio_7d_30d           0.0
13                     hour           0.0
14      log_mean_amount_30d           0.0
15       amount_to_mean_30d           0.0
16    log_amount_to_max_30d           0.0
17             amount_z_30d           0.0
18      night_unusual_score           0.0
19                 currency           0.0
20          payment_channel           0.0
21         merchant_country           0.0
22                      mcc           0.0
23          card_entry_mode           0.0
24              auth_result           0.0
25         pin_verif_method           0.0
26           recurring_flag           0.0
27     auth_characteristics           0.0
28             message_type           0.0
29            term_location           0.0
30                 day_name           0.0
31              time_period           0.0
32        night_ratio_group           0.0
33      night_unusual_group           0.0
34      amount_to_max_group           0.0
35      ip_score_risk_group           0.0
36  decline_rate_risk_group           0.0
37   credit_util_risk_group           0.0
38       txn_count_7d_group           0.0
39       txn_velocity_group           0.0

In [7]:
numeric_features = metadata["numeric_features"]
corr = train_df[numeric_features].corr(numeric_only=True)

corr_abs_pairs = (
    corr.abs()
    .where(np.triu(np.ones(corr.shape), k=1).astype(bool))
    .stack()
    .sort_values(ascending=False)
    .reset_index()
)
corr_abs_pairs.columns = ["feature_1", "feature_2", "abs_corr"]

display(corr_abs_pairs.head(30))

                 feature_1               feature_2  abs_corr
0       amount_to_mean_30d            amount_z_30d  0.764547
1            txn_count_30d  txn_count_ratio_7d_30d  0.593468
2       amount_to_mean_30d   log_amount_to_max_30d  0.389256
3             txn_count_7d  txn_count_ratio_7d_30d  0.383177
4    log_amount_to_max_30d            amount_z_30d  0.366764
5      log_mean_amount_30d      amount_to_mean_30d  0.362353
6          night_ratio_30d     night_unusual_score  0.338724
7                     hour     night_unusual_score  0.327516
8             txn_count_7d           txn_count_30d  0.251589
9          night_ratio_30d            amount_z_30d  0.013876
10         night_ratio_30d   log_amount_to_max_30d  0.012698
11         night_ratio_30d      amount_to_mean_30d  0.010821
12    device_diversity_30d  txn_count_ratio_7d_30d  0.009720
13  distinct_countries_30d                ip_score  0.009670
14  distinct_countries_30d           txn_count_30d  0.009347
15  distinct_countries_30d     log_mean_amount_30d  0.009158
16                    hour   log_amount_to_max_30d  0.008658
17    device_diversity_30d           txn_count_30d  0.007898
18            txn_count_7d     log_mean_amount_30d  0.007757
19         mcc_entropy_30d        decline_rate_30d  0.007179
20   distinct_merchants_7d     night_unusual_score  0.007153
21          spending_trend     night_unusual_score  0.007103
22  distinct_countries_30d  txn_count_ratio_7d_30d  0.006837
23   distinct_merchants_7d     log_mean_amount_30d  0.006538
24    device_diversity_30d     night_unusual_score  0.006515
25  txn_count_ratio_7d_30d            amount_z_30d  0.006279
26           txn_count_30d      amount_to_mean_30d  0.006121
27   distinct_merchants_7d        chargebacks_365d  0.005812
28  distinct_countries_30d    device_diversity_30d  0.005782
29        chargebacks_365d     log_mean_amount_30d  0.005769

In [8]:
print("Dropped columns:", metadata.get("dropped_columns"))
print("Thresholds:", metadata.get("thresholds"))

Dropped columns: ['ip_risk', 'txn_counts', 'ip_address', 'transaction_datetime']
Thresholds: {'very_low_mcc_entropy_q05': 0.197, 'low_mcc_entropy_q10': 0.393, 'low_night_ratio_q10': 0.101, 'high_max_amount_q90': 225176.777, 'low_spending_trend_q10': 0.584, 'low_country_diversity_q10': 3.0, 'high_device_diversity_q90': 36.0, 'high_decline_rate_q90': 0.283, 'high_ip_score_q90': 0.5123}

## Kết luận cần ghi sau khi chạy

            - Feature set đã đủ cho model chưa?
            - Có feature missing bất thường không?
            - Có feature tương quan cao cần loại cho Logistic Regression không?
            - Với CatBoost, interaction thủ công có thể bỏ được không?